"""Deterministic synthetic DDI datasets for polypharmacy triage tasks."""

from __future__ import annotations

from typing import Dict, List

SEVERITY_WEIGHTS: Dict[str, float] = {
    "contraindicated": 1.0,
    "major": 0.8,
    "moderate": 0.45,
    "minor": 0.2,
}

INTERACTION_RECOMMENDATIONS: Dict[str, str] = {
    "contraindicated": "flag_interaction",
    "major": "flag_interaction",
    "moderate": "monitor",
    "minor": "ignore",
}

TASK_CASES: Dict[str, List[Dict]] = {
    "easy": [
        {
            "case_id": "E-001",
            "age": 74,
            "labs": {"egfr": 68.0, "creatinine": 1.0, "potassium": 4.4, "inr": 2.4},
            "diagnoses": ["atrial_fibrillation", "hypertension", "dyslipidemia"],
            "medications": [
                "warfarin",
                "trimethoprim_sulfamethoxazole",
                "simvastatin",
                "amlodipine",
                "aspirin",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-E1",
                    "drug_a": "warfarin",
                    "drug_b": "trimethoprim_sulfamethoxazole",
                    "severity": "contraindicated",
                    "evidence": "increased INR and major bleeding risk",
                },
                {
                    "interaction_id": "INT-E2",
                    "drug_a": "warfarin",
                    "drug_b": "aspirin",
                    "severity": "major",
                    "evidence": "additive anticoagulation and bleeding",
                },
                {
                    "interaction_id": "INT-E3",
                    "drug_a": "simvastatin",
                    "drug_b": "amlodipine",
                    "severity": "moderate",
                    "evidence": "higher statin exposure and myopathy risk",
                },
            ],
            "required_regimens": [],
            "substitution_options": [],
        },
        {
            "case_id": "E-002",
            "age": 71,
            "labs": {"egfr": 74.0, "creatinine": 0.9, "potassium": 4.1, "inr": 1.1},
            "diagnoses": ["angina", "hypertension", "atrial_fibrillation"],
            "medications": [
                "nitroglycerin",
                "sildenafil",
                "apixaban",
                "clarithromycin",
                "metoprolol",
                "verapamil",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-E21",
                    "drug_a": "nitroglycerin",
                    "drug_b": "sildenafil",
                    "severity": "contraindicated",
                    "evidence": "profound hypotension risk from combined vasodilation",
                },
                {
                    "interaction_id": "INT-E22",
                    "drug_a": "apixaban",
                    "drug_b": "clarithromycin",
                    "severity": "major",
                    "evidence": "increased apixaban exposure and bleeding risk",
                },
                {
                    "interaction_id": "INT-E23",
                    "drug_a": "metoprolol",
                    "drug_b": "verapamil",
                    "severity": "moderate",
                    "evidence": "additive AV nodal blockade and bradycardia",
                },
            ],
            "required_regimens": [],
            "substitution_options": [],
        }
    ],
    "medium": [
        {
            "case_id": "M-001",
            "age": 83,
            "labs": {"egfr": 31.0, "creatinine": 2.0, "potassium": 5.4, "inr": 2.1},
            "diagnoses": [
                "heart_failure",
                "atrial_fibrillation",
                "type_2_diabetes",
                "chronic_kidney_disease",
            ],
            "medications": [
                "warfarin",
                "amiodarone",
                "spironolactone",
                "lisinopril",
                "furosemide",
                "metformin",
                "insulin_glargine",
                "atorvastatin",
                "omeprazole",
                "sertraline",
                "trimethoprim_sulfamethoxazole",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-M1",
                    "drug_a": "warfarin",
                    "drug_b": "amiodarone",
                    "severity": "major",
                    "evidence": "CYP inhibition elevates warfarin exposure",
                },
                {
                    "interaction_id": "INT-M2",
                    "drug_a": "spironolactone",
                    "drug_b": "lisinopril",
                    "severity": "moderate",
                    "evidence": "hyperkalemia risk with renal impairment",
                },
                {
                    "interaction_id": "INT-M3",
                    "drug_a": "metformin",
                    "drug_b": "furosemide",
                    "severity": "moderate",
                    "evidence": "reduced renal clearance can increase lactic acidosis risk",
                },
                {
                    "interaction_id": "INT-M4",
                    "drug_a": "warfarin",
                    "drug_b": "trimethoprim_sulfamethoxazole",
                    "severity": "contraindicated",
                    "evidence": "marked INR elevation and bleeding",
                },
            ],
            "required_regimens": [],
            "substitution_options": [],
        },
        {
            "case_id": "M-002",
            "age": 81,
            "labs": {"egfr": 38.0, "creatinine": 1.8, "potassium": 5.1, "inr": 2.0},
            "diagnoses": [
                "heart_failure",
                "atrial_fibrillation",
                "type_2_diabetes",
                "chronic_kidney_disease",
                "osteoarthritis",
            ],
            "medications": [
                "digoxin",
                "amiodarone",
                "spironolactone",
                "losartan",
                "rivaroxaban",
                "naproxen",
                "glipizide",
                "ciprofloxacin",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-M21",
                    "drug_a": "digoxin",
                    "drug_b": "amiodarone",
                    "severity": "major",
                    "evidence": "P-gp inhibition raises digoxin concentration",
                },
                {
                    "interaction_id": "INT-M22",
                    "drug_a": "spironolactone",
                    "drug_b": "losartan",
                    "severity": "moderate",
                    "evidence": "hyperkalemia risk increased in CKD",
                },
                {
                    "interaction_id": "INT-M23",
                    "drug_a": "rivaroxaban",
                    "drug_b": "naproxen",
                    "severity": "major",
                    "evidence": "additive bleeding risk with anticoagulant and NSAID",
                },
                {
                    "interaction_id": "INT-M24",
                    "drug_a": "glipizide",
                    "drug_b": "ciprofloxacin",
                    "severity": "moderate",
                    "evidence": "dysglycemia risk from fluoroquinolone-sulfonylurea combination",
                },
            ],
            "required_regimens": [],
            "substitution_options": [],
        }
    ],
    "hard": [
        {
            "case_id": "H-001",
            "age": 87,
            "labs": {"egfr": 26.0, "creatinine": 2.4, "potassium": 5.2, "inr": 2.6},
            "diagnoses": [
                "atrial_fibrillation",
                "coronary_artery_disease",
                "type_2_diabetes",
                "chronic_kidney_disease",
                "hypertension",
                "depression",
            ],
            "medications": [
                "warfarin",
                "trimethoprim_sulfamethoxazole",
                "clopidogrel",
                "omeprazole",
                "simvastatin",
                "amlodipine",
                "spironolactone",
                "lisinopril",
                "metformin",
                "insulin_glargine",
                "sertraline",
                "ibuprofen",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-H1",
                    "drug_a": "warfarin",
                    "drug_b": "trimethoprim_sulfamethoxazole",
                    "severity": "contraindicated",
                    "evidence": "severe bleeding risk due to INR elevation",
                },
                {
                    "interaction_id": "INT-H2",
                    "drug_a": "clopidogrel",
                    "drug_b": "omeprazole",
                    "severity": "major",
                    "evidence": "reduced clopidogrel activation and antiplatelet efficacy",
                },
                {
                    "interaction_id": "INT-H3",
                    "drug_a": "simvastatin",
                    "drug_b": "amlodipine",
                    "severity": "moderate",
                    "evidence": "myopathy risk from increased simvastatin exposure",
                },
                {
                    "interaction_id": "INT-H4",
                    "drug_a": "spironolactone",
                    "drug_b": "lisinopril",
                    "severity": "moderate",
                    "evidence": "hyperkalemia risk in CKD",
                },
                {
                    "interaction_id": "INT-H5",
                    "drug_a": "warfarin",
                    "drug_b": "ibuprofen",
                    "severity": "major",
                    "evidence": "substantial GI and systemic bleeding risk",
                },
            ],
            "required_regimens": ["REG-H1", "REG-H2", "REG-H3"],
            "substitution_options": [
                {
                    "regimen_id": "REG-H1",
                    "replace_drug": "trimethoprim_sulfamethoxazole",
                    "with_drug": "cephalexin",
                    "target_condition": "infection",
                    "expected_risk_delta": 0.85,
                    "rationale": "reduces anticoagulation interaction burden",
                },
                {
                    "regimen_id": "REG-H2",
                    "replace_drug": "omeprazole",
                    "with_drug": "pantoprazole",
                    "target_condition": "gi_protection",
                    "expected_risk_delta": 0.55,
                    "rationale": "lower impact on clopidogrel activation",
                },
                {
                    "regimen_id": "REG-H3",
                    "replace_drug": "ibuprofen",
                    "with_drug": "acetaminophen",
                    "target_condition": "pain",
                    "expected_risk_delta": 0.6,
                    "rationale": "reduces additive bleeding risk with warfarin",
                },
                {
                    "regimen_id": "REG-H4",
                    "replace_drug": "simvastatin",
                    "with_drug": "pravastatin",
                    "target_condition": "dyslipidemia",
                    "expected_risk_delta": 0.35,
                    "rationale": "less CYP3A4 interaction with amlodipine",
                },
            ],
        },
        {
            "case_id": "H-002",
            "age": 85,
            "labs": {"egfr": 24.0, "creatinine": 2.5, "potassium": 5.3, "inr": 2.8},
            "diagnoses": [
                "atrial_fibrillation",
                "peripheral_artery_disease",
                "type_2_diabetes",
                "chronic_kidney_disease",
                "hypertension",
                "chronic_pain",
            ],
            "medications": [
                "warfarin",
                "metronidazole",
                "ticagrelor",
                "omeprazole",
                "simvastatin",
                "diltiazem",
                "spironolactone",
                "valsartan",
                "metformin",
                "insulin_glargine",
                "sertraline",
                "diclofenac",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-H21",
                    "drug_a": "warfarin",
                    "drug_b": "metronidazole",
                    "severity": "contraindicated",
                    "evidence": "marked INR elevation with high bleeding risk",
                },
                {
                    "interaction_id": "INT-H22",
                    "drug_a": "ticagrelor",
                    "drug_b": "omeprazole",
                    "severity": "major",
                    "evidence": "potential reduction in antiplatelet effectiveness",
                },
                {
                    "interaction_id": "INT-H23",
                    "drug_a": "simvastatin",
                    "drug_b": "diltiazem",
                    "severity": "moderate",
                    "evidence": "increased statin exposure and myopathy risk",
                },
                {
                    "interaction_id": "INT-H24",
                    "drug_a": "spironolactone",
                    "drug_b": "valsartan",
                    "severity": "moderate",
                    "evidence": "hyperkalemia risk intensified by advanced CKD",
                },
                {
                    "interaction_id": "INT-H25",
                    "drug_a": "warfarin",
                    "drug_b": "diclofenac",
                    "severity": "major",
                    "evidence": "substantial gastrointestinal and systemic bleeding risk",
                },
            ],
            "required_regimens": ["REG-H21", "REG-H22", "REG-H23"],
            "substitution_options": [
                {
                    "regimen_id": "REG-H21",
                    "replace_drug": "metronidazole",
                    "with_drug": "doxycycline",
                    "target_condition": "infection",
                    "expected_risk_delta": 0.8,
                    "rationale": "reduces warfarin interaction burden",
                },
                {
                    "regimen_id": "REG-H22",
                    "replace_drug": "omeprazole",
                    "with_drug": "pantoprazole",
                    "target_condition": "gi_protection",
                    "expected_risk_delta": 0.55,
                    "rationale": "lower interaction burden with antiplatelet therapy",
                },
                {
                    "regimen_id": "REG-H23",
                    "replace_drug": "diclofenac",
                    "with_drug": "acetaminophen",
                    "target_condition": "pain",
                    "expected_risk_delta": 0.65,
                    "rationale": "reduces additive anticoagulation bleeding risk",
                },
                {
                    "regimen_id": "REG-H24",
                    "replace_drug": "simvastatin",
                    "with_drug": "rosuvastatin",
                    "target_condition": "dyslipidemia",
                    "expected_risk_delta": 0.3,
                    "rationale": "lower interaction risk with diltiazem",
                },
            ],
        }
    ],
}


# Additional deterministic cases to improve task diversity while preserving reproducibility.
TASK_CASES["easy"].extend(
    [
        {
            "case_id": "E-003",
            "age": 79,
            "labs": {"egfr": 45.0, "creatinine": 1.2, "potassium": 4.5, "inr": 1.0},
            "diagnoses": ["dyslipidemia", "hypertension", "hypothyroidism"],
            "medications": [
                "atorvastatin",
                "diltiazem",
                "dabigatran",
                "ketoconazole",
                "levothyroxine",
                "calcium_carbonate",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-E31",
                    "drug_a": "dabigatran",
                    "drug_b": "ketoconazole",
                    "severity": "major",
                    "evidence": "strong P-gp inhibition increases dabigatran exposure",
                },
                {
                    "interaction_id": "INT-E32",
                    "drug_a": "atorvastatin",
                    "drug_b": "diltiazem",
                    "severity": "moderate",
                    "evidence": "increased statin exposure and myopathy risk",
                },
                {
                    "interaction_id": "INT-E33",
                    "drug_a": "levothyroxine",
                    "drug_b": "calcium_carbonate",
                    "severity": "minor",
                    "evidence": "reduced levothyroxine absorption with coadministration",
                },
            ],
            "required_regimens": [],
            "substitution_options": [],
        },
        {
            "case_id": "E-004",
            "age": 66,
            "labs": {"egfr": 92.0, "creatinine": 0.8, "potassium": 4.2, "inr": 1.0},
            "diagnoses": ["depression", "hypertension", "iron_deficiency"],
            "medications": [
                "linezolid",
                "sertraline",
                "metoprolol",
                "paroxetine",
                "ferrous_sulfate",
                "levothyroxine",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-E41",
                    "drug_a": "linezolid",
                    "drug_b": "sertraline",
                    "severity": "major",
                    "evidence": "serotonergic toxicity risk from MAOI activity",
                },
                {
                    "interaction_id": "INT-E42",
                    "drug_a": "metoprolol",
                    "drug_b": "paroxetine",
                    "severity": "moderate",
                    "evidence": "CYP2D6 inhibition may increase beta-blocker effect",
                },
                {
                    "interaction_id": "INT-E43",
                    "drug_a": "ferrous_sulfate",
                    "drug_b": "levothyroxine",
                    "severity": "minor",
                    "evidence": "reduced thyroid hormone absorption",
                },
            ],
            "required_regimens": [],
            "substitution_options": [],
        },
        {
            "case_id": "E-005",
            "age": 84,
            "labs": {"egfr": 58.0, "creatinine": 1.3, "potassium": 4.8, "inr": 1.1},
            "diagnoses": ["angina", "heart_failure", "depression"],
            "medications": [
                "isosorbide_mononitrate",
                "sildenafil",
                "spironolactone",
                "losartan",
                "aspirin",
                "sertraline",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-E51",
                    "drug_a": "isosorbide_mononitrate",
                    "drug_b": "sildenafil",
                    "severity": "contraindicated",
                    "evidence": "severe hypotension from additive vasodilation",
                },
                {
                    "interaction_id": "INT-E52",
                    "drug_a": "spironolactone",
                    "drug_b": "losartan",
                    "severity": "moderate",
                    "evidence": "additive potassium retention",
                },
                {
                    "interaction_id": "INT-E53",
                    "drug_a": "aspirin",
                    "drug_b": "sertraline",
                    "severity": "minor",
                    "evidence": "mildly increased bleeding tendency",
                },
            ],
            "required_regimens": [],
            "substitution_options": [],
        },
        {
            "case_id": "E-006",
            "age": 72,
            "labs": {"egfr": 76.0, "creatinine": 0.9, "potassium": 4.3, "inr": 1.9},
            "diagnoses": ["atrial_fibrillation", "dyslipidemia", "infection"],
            "medications": [
                "apixaban",
                "clarithromycin",
                "simvastatin",
                "amlodipine",
                "cetirizine",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-E61",
                    "drug_a": "apixaban",
                    "drug_b": "clarithromycin",
                    "severity": "major",
                    "evidence": "increased anticoagulant exposure and bleeding risk",
                },
                {
                    "interaction_id": "INT-E62",
                    "drug_a": "simvastatin",
                    "drug_b": "amlodipine",
                    "severity": "moderate",
                    "evidence": "higher simvastatin exposure with myopathy risk",
                },
                {
                    "interaction_id": "INT-E63",
                    "drug_a": "cetirizine",
                    "drug_b": "amlodipine",
                    "severity": "minor",
                    "evidence": "possible additive dizziness in sensitive patients",
                },
            ],
            "required_regimens": [],
            "substitution_options": [],
        },
    ]
)

TASK_CASES["medium"].extend(
    [
        {
            "case_id": "M-003",
            "age": 79,
            "labs": {"egfr": 44.0, "creatinine": 1.7, "potassium": 5.0, "inr": 2.0},
            "diagnoses": ["heart_failure", "chronic_kidney_disease", "atrial_fibrillation"],
            "medications": [
                "spironolactone",
                "lisinopril",
                "metformin",
                "furosemide",
                "warfarin",
                "fluconazole",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-M31",
                    "drug_a": "spironolactone",
                    "drug_b": "lisinopril",
                    "severity": "moderate",
                    "evidence": "hyperkalemia risk in CKD",
                },
                {
                    "interaction_id": "INT-M32",
                    "drug_a": "metformin",
                    "drug_b": "furosemide",
                    "severity": "moderate",
                    "evidence": "renal stress may increase lactic acidosis risk",
                },
                {
                    "interaction_id": "INT-M33",
                    "drug_a": "warfarin",
                    "drug_b": "fluconazole",
                    "severity": "major",
                    "evidence": "CYP inhibition increases anticoagulant effect",
                },
                {
                    "interaction_id": "INT-M34",
                    "drug_a": "furosemide",
                    "drug_b": "warfarin",
                    "severity": "minor",
                    "evidence": "volume changes may alter INR stability",
                },
            ],
            "required_regimens": [],
            "substitution_options": [],
        },
        {
            "case_id": "M-004",
            "age": 80,
            "labs": {"egfr": 52.0, "creatinine": 1.3, "potassium": 4.7, "inr": 2.2},
            "diagnoses": ["atrial_fibrillation", "hypertension", "heart_failure"],
            "medications": [
                "digoxin",
                "verapamil",
                "spironolactone",
                "losartan",
                "warfarin",
                "amiodarone",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-M41",
                    "drug_a": "digoxin",
                    "drug_b": "verapamil",
                    "severity": "moderate",
                    "evidence": "P-gp inhibition can raise digoxin concentration",
                },
                {
                    "interaction_id": "INT-M42",
                    "drug_a": "spironolactone",
                    "drug_b": "losartan",
                    "severity": "moderate",
                    "evidence": "combined potassium retention",
                },
                {
                    "interaction_id": "INT-M43",
                    "drug_a": "warfarin",
                    "drug_b": "amiodarone",
                    "severity": "major",
                    "evidence": "CYP interaction elevates warfarin effect",
                },
                {
                    "interaction_id": "INT-M44",
                    "drug_a": "verapamil",
                    "drug_b": "losartan",
                    "severity": "minor",
                    "evidence": "possible additive hypotensive effect",
                },
            ],
            "required_regimens": [],
            "substitution_options": [],
        },
        {
            "case_id": "M-005",
            "age": 76,
            "labs": {"egfr": 61.0, "creatinine": 1.1, "potassium": 4.4, "inr": 2.1},
            "diagnoses": ["type_2_diabetes", "atrial_fibrillation", "dyslipidemia"],
            "medications": [
                "glipizide",
                "ciprofloxacin",
                "warfarin",
                "trimethoprim_sulfamethoxazole",
                "simvastatin",
                "amlodipine",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-M51",
                    "drug_a": "glipizide",
                    "drug_b": "ciprofloxacin",
                    "severity": "moderate",
                    "evidence": "dysglycemia risk from fluoroquinolone-sulfonylurea pair",
                },
                {
                    "interaction_id": "INT-M52",
                    "drug_a": "warfarin",
                    "drug_b": "trimethoprim_sulfamethoxazole",
                    "severity": "contraindicated",
                    "evidence": "marked INR elevation and bleeding risk",
                },
                {
                    "interaction_id": "INT-M53",
                    "drug_a": "simvastatin",
                    "drug_b": "amlodipine",
                    "severity": "moderate",
                    "evidence": "higher statin exposure and myopathy risk",
                },
                {
                    "interaction_id": "INT-M54",
                    "drug_a": "amlodipine",
                    "drug_b": "ciprofloxacin",
                    "severity": "minor",
                    "evidence": "possible additive hypotension in frail adults",
                },
            ],
            "required_regimens": [],
            "substitution_options": [],
        },
        {
            "case_id": "M-006",
            "age": 86,
            "labs": {"egfr": 29.0, "creatinine": 2.2, "potassium": 5.3, "inr": 2.3},
            "diagnoses": ["chronic_kidney_disease", "heart_failure", "depression"],
            "medications": [
                "spironolactone",
                "valsartan",
                "sertraline",
                "aspirin",
                "warfarin",
                "metronidazole",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-M61",
                    "drug_a": "spironolactone",
                    "drug_b": "valsartan",
                    "severity": "moderate",
                    "evidence": "high hyperkalemia risk in advanced CKD",
                },
                {
                    "interaction_id": "INT-M62",
                    "drug_a": "sertraline",
                    "drug_b": "aspirin",
                    "severity": "minor",
                    "evidence": "increased bleeding tendency, amplified in frailty",
                },
                {
                    "interaction_id": "INT-M63",
                    "drug_a": "warfarin",
                    "drug_b": "metronidazole",
                    "severity": "contraindicated",
                    "evidence": "substantial INR increase and severe bleeding risk",
                },
                {
                    "interaction_id": "INT-M64",
                    "drug_a": "aspirin",
                    "drug_b": "warfarin",
                    "severity": "major",
                    "evidence": "additive anticoagulation and bleeding",
                },
            ],
            "required_regimens": [],
            "substitution_options": [],
        },
    ]
)

TASK_CASES["hard"].extend(
    [
        {
            "case_id": "H-003",
            "age": 82,
            "labs": {"egfr": 45.0, "creatinine": 1.6, "potassium": 5.0, "inr": 2.4},
            "diagnoses": [
                "atrial_fibrillation",
                "coronary_artery_disease",
                "chronic_kidney_disease",
                "hypertension",
            ],
            "medications": [
                "warfarin",
                "fluconazole",
                "clopidogrel",
                "omeprazole",
                "simvastatin",
                "diltiazem",
                "spironolactone",
                "losartan",
                "ibuprofen",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-H31",
                    "drug_a": "warfarin",
                    "drug_b": "fluconazole",
                    "severity": "contraindicated",
                    "evidence": "major INR increase and bleeding risk",
                },
                {
                    "interaction_id": "INT-H32",
                    "drug_a": "clopidogrel",
                    "drug_b": "omeprazole",
                    "severity": "major",
                    "evidence": "reduced clopidogrel activation",
                },
                {
                    "interaction_id": "INT-H33",
                    "drug_a": "simvastatin",
                    "drug_b": "diltiazem",
                    "severity": "moderate",
                    "evidence": "myopathy risk from increased statin concentration",
                },
                {
                    "interaction_id": "INT-H34",
                    "drug_a": "spironolactone",
                    "drug_b": "losartan",
                    "severity": "moderate",
                    "evidence": "hyperkalemia risk in older adults",
                },
                {
                    "interaction_id": "INT-H35",
                    "drug_a": "warfarin",
                    "drug_b": "ibuprofen",
                    "severity": "major",
                    "evidence": "substantial additive bleeding risk",
                },
            ],
            "required_regimens": ["REG-H31", "REG-H32", "REG-H33"],
            "substitution_options": [
                {
                    "regimen_id": "REG-H31",
                    "replace_drug": "fluconazole",
                    "with_drug": "micafungin",
                    "target_condition": "infection",
                    "expected_risk_delta": 0.75,
                    "rationale": "reduces warfarin interaction burden",
                },
                {
                    "regimen_id": "REG-H32",
                    "replace_drug": "omeprazole",
                    "with_drug": "pantoprazole",
                    "target_condition": "gi_protection",
                    "expected_risk_delta": 0.52,
                    "rationale": "lower impact on clopidogrel activation",
                },
                {
                    "regimen_id": "REG-H33",
                    "replace_drug": "ibuprofen",
                    "with_drug": "acetaminophen",
                    "target_condition": "pain",
                    "expected_risk_delta": 0.62,
                    "rationale": "reduces additive bleeding risk with warfarin",
                },
                {
                    "regimen_id": "REG-H34",
                    "replace_drug": "simvastatin",
                    "with_drug": "pravastatin",
                    "target_condition": "dyslipidemia",
                    "expected_risk_delta": 0.35,
                    "rationale": "lower interaction burden with diltiazem",
                },
            ],
        },
        {
            "case_id": "H-004",
            "age": 78,
            "labs": {"egfr": 33.0, "creatinine": 2.0, "potassium": 5.1, "inr": 2.2},
            "diagnoses": [
                "atrial_fibrillation",
                "chronic_kidney_disease",
                "type_2_diabetes",
                "osteoarthritis",
            ],
            "medications": [
                "warfarin",
                "trimethoprim_sulfamethoxazole",
                "rivaroxaban",
                "naproxen",
                "spironolactone",
                "lisinopril",
                "metformin",
                "furosemide",
                "omeprazole",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-H41",
                    "drug_a": "warfarin",
                    "drug_b": "trimethoprim_sulfamethoxazole",
                    "severity": "contraindicated",
                    "evidence": "marked INR increase and severe bleeding risk",
                },
                {
                    "interaction_id": "INT-H42",
                    "drug_a": "rivaroxaban",
                    "drug_b": "naproxen",
                    "severity": "major",
                    "evidence": "additive anticoagulant-related bleeding risk",
                },
                {
                    "interaction_id": "INT-H43",
                    "drug_a": "spironolactone",
                    "drug_b": "lisinopril",
                    "severity": "moderate",
                    "evidence": "hyperkalemia risk amplified by CKD",
                },
                {
                    "interaction_id": "INT-H44",
                    "drug_a": "metformin",
                    "drug_b": "furosemide",
                    "severity": "moderate",
                    "evidence": "reduced renal reserve increases lactic acidosis risk",
                },
            ],
            "required_regimens": ["REG-H41", "REG-H42"],
            "substitution_options": [
                {
                    "regimen_id": "REG-H41",
                    "replace_drug": "trimethoprim_sulfamethoxazole",
                    "with_drug": "cefdinir",
                    "target_condition": "infection",
                    "expected_risk_delta": 0.78,
                    "rationale": "reduces warfarin interaction burden",
                },
                {
                    "regimen_id": "REG-H42",
                    "replace_drug": "naproxen",
                    "with_drug": "acetaminophen",
                    "target_condition": "pain",
                    "expected_risk_delta": 0.58,
                    "rationale": "reduces additive bleeding risk",
                },
                {
                    "regimen_id": "REG-H43",
                    "replace_drug": "omeprazole",
                    "with_drug": "pantoprazole",
                    "target_condition": "gi_protection",
                    "expected_risk_delta": 0.3,
                    "rationale": "modest interaction reduction",
                },
            ],
        },
        {
            "case_id": "H-005",
            "age": 89,
            "labs": {"egfr": 28.0, "creatinine": 2.3, "potassium": 5.4, "inr": 2.7},
            "diagnoses": [
                "atrial_fibrillation",
                "chronic_kidney_disease",
                "depression",
                "chronic_pain",
            ],
            "medications": [
                "warfarin",
                "metronidazole",
                "aspirin",
                "sertraline",
                "spironolactone",
                "valsartan",
                "simvastatin",
                "amlodipine",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-H51",
                    "drug_a": "warfarin",
                    "drug_b": "metronidazole",
                    "severity": "contraindicated",
                    "evidence": "high likelihood of severe INR elevation",
                },
                {
                    "interaction_id": "INT-H52",
                    "drug_a": "aspirin",
                    "drug_b": "sertraline",
                    "severity": "minor",
                    "evidence": "bleeding tendency becomes clinically meaningful in frailty",
                },
                {
                    "interaction_id": "INT-H53",
                    "drug_a": "spironolactone",
                    "drug_b": "valsartan",
                    "severity": "moderate",
                    "evidence": "severe hyperkalemia risk in advanced CKD",
                },
                {
                    "interaction_id": "INT-H54",
                    "drug_a": "simvastatin",
                    "drug_b": "amlodipine",
                    "severity": "moderate",
                    "evidence": "myopathy risk from increased statin exposure",
                },
            ],
            "required_regimens": ["REG-H51", "REG-H52", "REG-H53"],
            "substitution_options": [
                {
                    "regimen_id": "REG-H51",
                    "replace_drug": "metronidazole",
                    "with_drug": "doxycycline",
                    "target_condition": "infection",
                    "expected_risk_delta": 0.82,
                    "rationale": "reduces warfarin interaction burden",
                },
                {
                    "regimen_id": "REG-H52",
                    "replace_drug": "aspirin",
                    "with_drug": "none",
                    "target_condition": "primary_prevention",
                    "expected_risk_delta": 0.5,
                    "rationale": "removes avoidable additive bleeding risk",
                },
                {
                    "regimen_id": "REG-H53",
                    "replace_drug": "simvastatin",
                    "with_drug": "rosuvastatin",
                    "target_condition": "dyslipidemia",
                    "expected_risk_delta": 0.34,
                    "rationale": "lower interaction burden with calcium channel blocker",
                },
            ],
        },
        {
            "case_id": "H-006",
            "age": 73,
            "labs": {"egfr": 41.0, "creatinine": 1.9, "potassium": 4.9, "inr": 2.1},
            "diagnoses": [
                "atrial_fibrillation",
                "chronic_kidney_disease",
                "dyslipidemia",
                "hypertension",
            ],
            "medications": [
                "apixaban",
                "clarithromycin",
                "clopidogrel",
                "omeprazole",
                "spironolactone",
                "lisinopril",
                "diclofenac",
            ],
            "interactions": [
                {
                    "interaction_id": "INT-H61",
                    "drug_a": "apixaban",
                    "drug_b": "clarithromycin",
                    "severity": "major",
                    "evidence": "increased anticoagulant exposure and bleeding risk",
                },
                {
                    "interaction_id": "INT-H62",
                    "drug_a": "clopidogrel",
                    "drug_b": "omeprazole",
                    "severity": "major",
                    "evidence": "reduced antiplatelet activation",
                },
                {
                    "interaction_id": "INT-H63",
                    "drug_a": "spironolactone",
                    "drug_b": "lisinopril",
                    "severity": "moderate",
                    "evidence": "hyperkalemia risk with reduced kidney function",
                },
                {
                    "interaction_id": "INT-H64",
                    "drug_a": "apixaban",
                    "drug_b": "diclofenac",
                    "severity": "major",
                    "evidence": "substantial additive bleeding risk",
                },
            ],
            "required_regimens": ["REG-H61", "REG-H62", "REG-H63"],
            "substitution_options": [
                {
                    "regimen_id": "REG-H61",
                    "replace_drug": "clarithromycin",
                    "with_drug": "azithromycin",
                    "target_condition": "infection",
                    "expected_risk_delta": 0.67,
                    "rationale": "lower CYP3A4 interaction burden",
                },
                {
                    "regimen_id": "REG-H62",
                    "replace_drug": "omeprazole",
                    "with_drug": "pantoprazole",
                    "target_condition": "gi_protection",
                    "expected_risk_delta": 0.54,
                    "rationale": "reduces clopidogrel interaction",
                },
                {
                    "regimen_id": "REG-H63",
                    "replace_drug": "diclofenac",
                    "with_drug": "acetaminophen",
                    "target_condition": "pain",
                    "expected_risk_delta": 0.59,
                    "rationale": "reduces additive bleeding risk with anticoagulation",
                },
                {
                    "regimen_id": "REG-H64",
                    "replace_drug": "spironolactone",
                    "with_drug": "eplerenone",
                    "target_condition": "heart_failure",
                    "expected_risk_delta": 0.32,
                    "rationale": "modest improvement in hyperkalemia risk profile",
                },
            ],
        },
    ]
)
