"""Deterministic DDI cases for the easy task level."""

from typing import Any, Dict, List

Case = Dict[str, Any]

EASY_CASES: List[Case] = [
    {
        "case_id": "E-001",
        "age": 74,
        "labs": {"egfr": 68.0, "creatinine": 1.0, "potassium": 4.4, "inr": 2.4},
        "diagnoses": ["atrial_fibrillation", "hypertension", "dyslipidemia"],
        "medications": [
            "warfarin",
            "trimethoprim_sulfamethoxazole",
            "simvastatin",
            "amlodipine",
            "aspirin",
        ],
        "interactions": [
            {
                "interaction_id": "INT-E1",
                "drug_a": "warfarin",
                "drug_b": "trimethoprim_sulfamethoxazole",
                "severity": "contraindicated",
                "evidence": "increased INR and major bleeding risk",
            },
            {
                "interaction_id": "INT-E2",
                "drug_a": "warfarin",
                "drug_b": "aspirin",
                "severity": "major",
                "evidence": "additive anticoagulation and bleeding",
            },
            {
                "interaction_id": "INT-E3",
                "drug_a": "simvastatin",
                "drug_b": "amlodipine",
                "severity": "moderate",
                "evidence": "higher statin exposure and myopathy risk",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
    {
        "case_id": "E-002",
        "age": 71,
        "labs": {"egfr": 74.0, "creatinine": 0.9, "potassium": 4.1, "inr": 1.1},
        "diagnoses": ["angina", "hypertension", "atrial_fibrillation"],
        "medications": [
            "nitroglycerin",
            "sildenafil",
            "apixaban",
            "clarithromycin",
            "metoprolol",
            "verapamil",
        ],
        "interactions": [
            {
                "interaction_id": "INT-E21",
                "drug_a": "nitroglycerin",
                "drug_b": "sildenafil",
                "severity": "contraindicated",
                "evidence": "profound hypotension risk from combined vasodilation",
            },
            {
                "interaction_id": "INT-E22",
                "drug_a": "apixaban",
                "drug_b": "clarithromycin",
                "severity": "major",
                "evidence": "increased apixaban exposure and bleeding risk",
            },
            {
                "interaction_id": "INT-E23",
                "drug_a": "metoprolol",
                "drug_b": "verapamil",
                "severity": "moderate",
                "evidence": "additive AV nodal blockade and bradycardia",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
    {
        "case_id": "E-003",
        "age": 79,
        "labs": {"egfr": 45.0, "creatinine": 1.2, "potassium": 4.5, "inr": 1.0},
        "diagnoses": ["dyslipidemia", "hypertension", "hypothyroidism"],
        "medications": [
            "atorvastatin",
            "diltiazem",
            "dabigatran",
            "ketoconazole",
            "levothyroxine",
            "calcium_carbonate",
        ],
        "interactions": [
            {
                "interaction_id": "INT-E31",
                "drug_a": "dabigatran",
                "drug_b": "ketoconazole",
                "severity": "major",
                "evidence": "strong P-gp inhibition increases dabigatran exposure",
            },
            {
                "interaction_id": "INT-E32",
                "drug_a": "atorvastatin",
                "drug_b": "diltiazem",
                "severity": "moderate",
                "evidence": "increased statin exposure and myopathy risk",
            },
            {
                "interaction_id": "INT-E33",
                "drug_a": "levothyroxine",
                "drug_b": "calcium_carbonate",
                "severity": "minor",
                "evidence": "reduced levothyroxine absorption with coadministration",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
    {
        "case_id": "E-004",
        "age": 66,
        "labs": {"egfr": 92.0, "creatinine": 0.8, "potassium": 4.2, "inr": 1.0},
        "diagnoses": ["depression", "hypertension", "iron_deficiency"],
        "medications": [
            "linezolid",
            "sertraline",
            "metoprolol",
            "paroxetine",
            "ferrous_sulfate",
            "levothyroxine",
        ],
        "interactions": [
            {
                "interaction_id": "INT-E41",
                "drug_a": "linezolid",
                "drug_b": "sertraline",
                "severity": "major",
                "evidence": "serotonergic toxicity risk from MAOI activity",
            },
            {
                "interaction_id": "INT-E42",
                "drug_a": "metoprolol",
                "drug_b": "paroxetine",
                "severity": "moderate",
                "evidence": "CYP2D6 inhibition may increase beta-blocker effect",
            },
            {
                "interaction_id": "INT-E43",
                "drug_a": "ferrous_sulfate",
                "drug_b": "levothyroxine",
                "severity": "minor",
                "evidence": "reduced thyroid hormone absorption",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
    {
        "case_id": "E-005",
        "age": 84,
        "labs": {"egfr": 58.0, "creatinine": 1.3, "potassium": 4.8, "inr": 1.1},
        "diagnoses": ["angina", "heart_failure", "depression"],
        "medications": [
            "isosorbide_mononitrate",
            "sildenafil",
            "spironolactone",
            "losartan",
            "aspirin",
            "sertraline",
        ],
        "interactions": [
            {
                "interaction_id": "INT-E51",
                "drug_a": "isosorbide_mononitrate",
                "drug_b": "sildenafil",
                "severity": "contraindicated",
                "evidence": "severe hypotension from additive vasodilation",
            },
            {
                "interaction_id": "INT-E52",
                "drug_a": "spironolactone",
                "drug_b": "losartan",
                "severity": "moderate",
                "evidence": "additive potassium retention",
            },
            {
                "interaction_id": "INT-E53",
                "drug_a": "aspirin",
                "drug_b": "sertraline",
                "severity": "minor",
                "evidence": "mildly increased bleeding tendency",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
    {
        "case_id": "E-006",
        "age": 72,
        "labs": {"egfr": 76.0, "creatinine": 0.9, "potassium": 4.3, "inr": 1.9},
        "diagnoses": ["atrial_fibrillation", "dyslipidemia", "infection"],
        "medications": [
            "apixaban",
            "clarithromycin",
            "simvastatin",
            "amlodipine",
            "cetirizine",
        ],
        "interactions": [
            {
                "interaction_id": "INT-E61",
                "drug_a": "apixaban",
                "drug_b": "clarithromycin",
                "severity": "major",
                "evidence": "increased anticoagulant exposure and bleeding risk",
            },
            {
                "interaction_id": "INT-E62",
                "drug_a": "simvastatin",
                "drug_b": "amlodipine",
                "severity": "moderate",
                "evidence": "higher simvastatin exposure with myopathy risk",
            },
            {
                "interaction_id": "INT-E63",
                "drug_a": "cetirizine",
                "drug_b": "amlodipine",
                "severity": "minor",
                "evidence": "possible additive dizziness in sensitive patients",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
]
