"""Deterministic DDI cases for the hard task level."""

from typing import Any, Dict, List

Case = Dict[str, Any]

HARD_CASES: List[Case] = [
    {
        "case_id": "H-001",
        "age": 87,
        "labs": {"egfr": 26.0, "creatinine": 2.4, "potassium": 5.2, "inr": 2.6},
        "diagnoses": [
            "atrial_fibrillation",
            "coronary_artery_disease",
            "type_2_diabetes",
            "chronic_kidney_disease",
            "hypertension",
            "depression",
        ],
        "medications": [
            "warfarin",
            "trimethoprim_sulfamethoxazole",
            "clopidogrel",
            "omeprazole",
            "simvastatin",
            "amlodipine",
            "spironolactone",
            "lisinopril",
            "metformin",
            "insulin_glargine",
            "sertraline",
            "ibuprofen",
        ],
        "interactions": [
            {
                "interaction_id": "INT-H1",
                "drug_a": "warfarin",
                "drug_b": "trimethoprim_sulfamethoxazole",
                "severity": "contraindicated",
                "evidence": "severe bleeding risk due to INR elevation",
            },
            {
                "interaction_id": "INT-H2",
                "drug_a": "clopidogrel",
                "drug_b": "omeprazole",
                "severity": "major",
                "evidence": "reduced clopidogrel activation and antiplatelet efficacy",
            },
            {
                "interaction_id": "INT-H3",
                "drug_a": "simvastatin",
                "drug_b": "amlodipine",
                "severity": "moderate",
                "evidence": "myopathy risk from increased simvastatin exposure",
            },
            {
                "interaction_id": "INT-H4",
                "drug_a": "spironolactone",
                "drug_b": "lisinopril",
                "severity": "moderate",
                "evidence": "hyperkalemia risk in CKD",
            },
            {
                "interaction_id": "INT-H5",
                "drug_a": "warfarin",
                "drug_b": "ibuprofen",
                "severity": "major",
                "evidence": "substantial GI and systemic bleeding risk",
            },
        ],
        "required_regimens": ["REG-H1", "REG-H2", "REG-H3"],
        "substitution_options": [
            {
                "regimen_id": "REG-H1",
                "replace_drug": "trimethoprim_sulfamethoxazole",
                "with_drug": "cephalexin",
                "target_condition": "infection",
                "expected_risk_delta": 0.85,
                "rationale": "reduces anticoagulation interaction burden",
            },
            {
                "regimen_id": "REG-H2",
                "replace_drug": "omeprazole",
                "with_drug": "pantoprazole",
                "target_condition": "gi_protection",
                "expected_risk_delta": 0.55,
                "rationale": "lower impact on clopidogrel activation",
            },
            {
                "regimen_id": "REG-H3",
                "replace_drug": "ibuprofen",
                "with_drug": "acetaminophen",
                "target_condition": "pain",
                "expected_risk_delta": 0.6,
                "rationale": "reduces additive bleeding risk with warfarin",
            },
            {
                "regimen_id": "REG-H4",
                "replace_drug": "simvastatin",
                "with_drug": "pravastatin",
                "target_condition": "dyslipidemia",
                "expected_risk_delta": 0.35,
                "rationale": "less CYP3A4 interaction with amlodipine",
            },
        ],
    },
    {
        "case_id": "H-002",
        "age": 85,
        "labs": {"egfr": 24.0, "creatinine": 2.5, "potassium": 5.3, "inr": 2.8},
        "diagnoses": [
            "atrial_fibrillation",
            "peripheral_artery_disease",
            "type_2_diabetes",
            "chronic_kidney_disease",
            "hypertension",
            "chronic_pain",
        ],
        "medications": [
            "warfarin",
            "metronidazole",
            "ticagrelor",
            "omeprazole",
            "simvastatin",
            "diltiazem",
            "spironolactone",
            "valsartan",
            "metformin",
            "insulin_glargine",
            "sertraline",
            "diclofenac",
        ],
        "interactions": [
            {
                "interaction_id": "INT-H21",
                "drug_a": "warfarin",
                "drug_b": "metronidazole",
                "severity": "contraindicated",
                "evidence": "marked INR elevation with high bleeding risk",
            },
            {
                "interaction_id": "INT-H22",
                "drug_a": "ticagrelor",
                "drug_b": "omeprazole",
                "severity": "major",
                "evidence": "potential reduction in antiplatelet effectiveness",
            },
            {
                "interaction_id": "INT-H23",
                "drug_a": "simvastatin",
                "drug_b": "diltiazem",
                "severity": "moderate",
                "evidence": "increased statin exposure and myopathy risk",
            },
            {
                "interaction_id": "INT-H24",
                "drug_a": "spironolactone",
                "drug_b": "valsartan",
                "severity": "moderate",
                "evidence": "hyperkalemia risk intensified by advanced CKD",
            },
            {
                "interaction_id": "INT-H25",
                "drug_a": "warfarin",
                "drug_b": "diclofenac",
                "severity": "major",
                "evidence": "substantial gastrointestinal and systemic bleeding risk",
            },
        ],
        "required_regimens": ["REG-H21", "REG-H22", "REG-H23"],
        "substitution_options": [
            {
                "regimen_id": "REG-H21",
                "replace_drug": "metronidazole",
                "with_drug": "doxycycline",
                "target_condition": "infection",
                "expected_risk_delta": 0.8,
                "rationale": "reduces warfarin interaction burden",
            },
            {
                "regimen_id": "REG-H22",
                "replace_drug": "omeprazole",
                "with_drug": "pantoprazole",
                "target_condition": "gi_protection",
                "expected_risk_delta": 0.55,
                "rationale": "lower interaction burden with antiplatelet therapy",
            },
            {
                "regimen_id": "REG-H23",
                "replace_drug": "diclofenac",
                "with_drug": "acetaminophen",
                "target_condition": "pain",
                "expected_risk_delta": 0.65,
                "rationale": "reduces additive anticoagulation bleeding risk",
            },
            {
                "regimen_id": "REG-H24",
                "replace_drug": "simvastatin",
                "with_drug": "rosuvastatin",
                "target_condition": "dyslipidemia",
                "expected_risk_delta": 0.3,
                "rationale": "lower interaction risk with diltiazem",
            },
        ],
    },
    {
        "case_id": "H-003",
        "age": 82,
        "labs": {"egfr": 45.0, "creatinine": 1.6, "potassium": 5.0, "inr": 2.4},
        "diagnoses": [
            "atrial_fibrillation",
            "coronary_artery_disease",
            "chronic_kidney_disease",
            "hypertension",
        ],
        "medications": [
            "warfarin",
            "fluconazole",
            "clopidogrel",
            "omeprazole",
            "simvastatin",
            "diltiazem",
            "spironolactone",
            "losartan",
            "ibuprofen",
        ],
        "interactions": [
            {
                "interaction_id": "INT-H31",
                "drug_a": "warfarin",
                "drug_b": "fluconazole",
                "severity": "contraindicated",
                "evidence": "major INR increase and bleeding risk",
            },
            {
                "interaction_id": "INT-H32",
                "drug_a": "clopidogrel",
                "drug_b": "omeprazole",
                "severity": "major",
                "evidence": "reduced clopidogrel activation",
            },
            {
                "interaction_id": "INT-H33",
                "drug_a": "simvastatin",
                "drug_b": "diltiazem",
                "severity": "moderate",
                "evidence": "myopathy risk from increased statin concentration",
            },
            {
                "interaction_id": "INT-H34",
                "drug_a": "spironolactone",
                "drug_b": "losartan",
                "severity": "moderate",
                "evidence": "hyperkalemia risk in older adults",
            },
            {
                "interaction_id": "INT-H35",
                "drug_a": "warfarin",
                "drug_b": "ibuprofen",
                "severity": "major",
                "evidence": "substantial additive bleeding risk",
            },
        ],
        "required_regimens": ["REG-H31", "REG-H32", "REG-H33"],
        "substitution_options": [
            {
                "regimen_id": "REG-H31",
                "replace_drug": "fluconazole",
                "with_drug": "micafungin",
                "target_condition": "infection",
                "expected_risk_delta": 0.75,
                "rationale": "reduces warfarin interaction burden",
            },
            {
                "regimen_id": "REG-H32",
                "replace_drug": "omeprazole",
                "with_drug": "pantoprazole",
                "target_condition": "gi_protection",
                "expected_risk_delta": 0.52,
                "rationale": "lower impact on clopidogrel activation",
            },
            {
                "regimen_id": "REG-H33",
                "replace_drug": "ibuprofen",
                "with_drug": "acetaminophen",
                "target_condition": "pain",
                "expected_risk_delta": 0.62,
                "rationale": "reduces additive bleeding risk with warfarin",
            },
            {
                "regimen_id": "REG-H34",
                "replace_drug": "simvastatin",
                "with_drug": "pravastatin",
                "target_condition": "dyslipidemia",
                "expected_risk_delta": 0.35,
                "rationale": "lower interaction burden with diltiazem",
            },
        ],
    },
    {
        "case_id": "H-004",
        "age": 78,
        "labs": {"egfr": 33.0, "creatinine": 2.0, "potassium": 5.1, "inr": 2.2},
        "diagnoses": [
            "atrial_fibrillation",
            "chronic_kidney_disease",
            "type_2_diabetes",
            "osteoarthritis",
        ],
        "medications": [
            "warfarin",
            "trimethoprim_sulfamethoxazole",
            "rivaroxaban",
            "naproxen",
            "spironolactone",
            "lisinopril",
            "metformin",
            "furosemide",
            "omeprazole",
        ],
        "interactions": [
            {
                "interaction_id": "INT-H41",
                "drug_a": "warfarin",
                "drug_b": "trimethoprim_sulfamethoxazole",
                "severity": "contraindicated",
                "evidence": "marked INR increase and severe bleeding risk",
            },
            {
                "interaction_id": "INT-H42",
                "drug_a": "rivaroxaban",
                "drug_b": "naproxen",
                "severity": "major",
                "evidence": "additive anticoagulant-related bleeding risk",
            },
            {
                "interaction_id": "INT-H43",
                "drug_a": "spironolactone",
                "drug_b": "lisinopril",
                "severity": "moderate",
                "evidence": "hyperkalemia risk amplified by CKD",
            },
            {
                "interaction_id": "INT-H44",
                "drug_a": "metformin",
                "drug_b": "furosemide",
                "severity": "moderate",
                "evidence": "reduced renal reserve increases lactic acidosis risk",
            },
        ],
        "required_regimens": ["REG-H41", "REG-H42"],
        "substitution_options": [
            {
                "regimen_id": "REG-H41",
                "replace_drug": "trimethoprim_sulfamethoxazole",
                "with_drug": "cefdinir",
                "target_condition": "infection",
                "expected_risk_delta": 0.78,
                "rationale": "reduces warfarin interaction burden",
            },
            {
                "regimen_id": "REG-H42",
                "replace_drug": "naproxen",
                "with_drug": "acetaminophen",
                "target_condition": "pain",
                "expected_risk_delta": 0.58,
                "rationale": "reduces additive bleeding risk",
            },
            {
                "regimen_id": "REG-H43",
                "replace_drug": "omeprazole",
                "with_drug": "pantoprazole",
                "target_condition": "gi_protection",
                "expected_risk_delta": 0.3,
                "rationale": "modest interaction reduction",
            },
        ],
    },
    {
        "case_id": "H-005",
        "age": 89,
        "labs": {"egfr": 28.0, "creatinine": 2.3, "potassium": 5.4, "inr": 2.7},
        "diagnoses": [
            "atrial_fibrillation",
            "chronic_kidney_disease",
            "depression",
            "chronic_pain",
        ],
        "medications": [
            "warfarin",
            "metronidazole",
            "aspirin",
            "sertraline",
            "spironolactone",
            "valsartan",
            "simvastatin",
            "amlodipine",
        ],
        "interactions": [
            {
                "interaction_id": "INT-H51",
                "drug_a": "warfarin",
                "drug_b": "metronidazole",
                "severity": "contraindicated",
                "evidence": "high likelihood of severe INR elevation",
            },
            {
                "interaction_id": "INT-H52",
                "drug_a": "aspirin",
                "drug_b": "sertraline",
                "severity": "minor",
                "evidence": "bleeding tendency becomes clinically meaningful in frailty",
            },
            {
                "interaction_id": "INT-H53",
                "drug_a": "spironolactone",
                "drug_b": "valsartan",
                "severity": "moderate",
                "evidence": "severe hyperkalemia risk in advanced CKD",
            },
            {
                "interaction_id": "INT-H54",
                "drug_a": "simvastatin",
                "drug_b": "amlodipine",
                "severity": "moderate",
                "evidence": "myopathy risk from increased statin exposure",
            },
        ],
        "required_regimens": ["REG-H51", "REG-H52", "REG-H53"],
        "substitution_options": [
            {
                "regimen_id": "REG-H51",
                "replace_drug": "metronidazole",
                "with_drug": "doxycycline",
                "target_condition": "infection",
                "expected_risk_delta": 0.82,
                "rationale": "reduces warfarin interaction burden",
            },
            {
                "regimen_id": "REG-H52",
                "replace_drug": "aspirin",
                "with_drug": "none",
                "target_condition": "primary_prevention",
                "expected_risk_delta": 0.5,
                "rationale": "removes avoidable additive bleeding risk",
            },
            {
                "regimen_id": "REG-H53",
                "replace_drug": "simvastatin",
                "with_drug": "rosuvastatin",
                "target_condition": "dyslipidemia",
                "expected_risk_delta": 0.34,
                "rationale": "lower interaction burden with calcium channel blocker",
            },
        ],
    },
    {
        "case_id": "H-006",
        "age": 73,
        "labs": {"egfr": 41.0, "creatinine": 1.9, "potassium": 4.9, "inr": 2.1},
        "diagnoses": [
            "atrial_fibrillation",
            "chronic_kidney_disease",
            "dyslipidemia",
            "hypertension",
        ],
        "medications": [
            "apixaban",
            "clarithromycin",
            "clopidogrel",
            "omeprazole",
            "spironolactone",
            "lisinopril",
            "diclofenac",
        ],
        "interactions": [
            {
                "interaction_id": "INT-H61",
                "drug_a": "apixaban",
                "drug_b": "clarithromycin",
                "severity": "major",
                "evidence": "increased anticoagulant exposure and bleeding risk",
            },
            {
                "interaction_id": "INT-H62",
                "drug_a": "clopidogrel",
                "drug_b": "omeprazole",
                "severity": "major",
                "evidence": "reduced antiplatelet activation",
            },
            {
                "interaction_id": "INT-H63",
                "drug_a": "spironolactone",
                "drug_b": "lisinopril",
                "severity": "moderate",
                "evidence": "hyperkalemia risk with reduced kidney function",
            },
            {
                "interaction_id": "INT-H64",
                "drug_a": "apixaban",
                "drug_b": "diclofenac",
                "severity": "major",
                "evidence": "substantial additive bleeding risk",
            },
        ],
        "required_regimens": ["REG-H61", "REG-H62", "REG-H63"],
        "substitution_options": [
            {
                "regimen_id": "REG-H61",
                "replace_drug": "clarithromycin",
                "with_drug": "azithromycin",
                "target_condition": "infection",
                "expected_risk_delta": 0.67,
                "rationale": "lower CYP3A4 interaction burden",
            },
            {
                "regimen_id": "REG-H62",
                "replace_drug": "omeprazole",
                "with_drug": "pantoprazole",
                "target_condition": "gi_protection",
                "expected_risk_delta": 0.54,
                "rationale": "reduces clopidogrel interaction",
            },
            {
                "regimen_id": "REG-H63",
                "replace_drug": "diclofenac",
                "with_drug": "acetaminophen",
                "target_condition": "pain",
                "expected_risk_delta": 0.59,
                "rationale": "reduces additive bleeding risk with anticoagulation",
            },
            {
                "regimen_id": "REG-H64",
                "replace_drug": "spironolactone",
                "with_drug": "eplerenone",
                "target_condition": "heart_failure",
                "expected_risk_delta": 0.32,
                "rationale": "modest improvement in hyperkalemia risk profile",
            },
        ],
    },
    {
        "case_id": "H-007",
        "template_family": "validation::hepatic-renal-anticoag-family",
        "split": "validation",
        "age": 81,
        "labs": {
            "egfr": 44.8,
            "creatinine": 1.8,
            "potassium": 5.0,
            "inr": 2.4,
            "alt": 126.0,
            "ast": 121.0,
        },
        "diagnoses": [
            "atrial_fibrillation",
            "chronic_kidney_disease",
            "chronic_liver_disease",
            "coronary_artery_disease",
            "chronic_pain",
        ],
        "medications": [
            "warfarin",
            "metronidazole",
            "clopidogrel",
            "omeprazole",
            "spironolactone",
            "losartan",
            "diclofenac",
            "diltiazem",
            "simvastatin",
        ],
        "interactions": [
            {
                "interaction_id": "INT-H71",
                "drug_a": "warfarin",
                "drug_b": "metronidazole",
                "severity": "contraindicated",
                "evidence": "pronounced INR elevation and major bleeding risk",
            },
            {
                "interaction_id": "INT-H72",
                "drug_a": "clopidogrel",
                "drug_b": "omeprazole",
                "severity": "major",
                "evidence": "reduced antiplatelet activation",
            },
            {
                "interaction_id": "INT-H73",
                "drug_a": "spironolactone",
                "drug_b": "losartan",
                "severity": "moderate",
                "evidence": "severe hyperkalemia risk in CKD",
            },
            {
                "interaction_id": "INT-H74",
                "drug_a": "simvastatin",
                "drug_b": "diltiazem",
                "severity": "moderate",
                "evidence": "higher statin exposure with myopathy risk",
            },
            {
                "interaction_id": "INT-H75",
                "drug_a": "warfarin",
                "drug_b": "diclofenac",
                "severity": "major",
                "evidence": "additive GI and systemic bleeding risk",
            },
        ],
        "required_regimens": ["REG-H71", "REG-H72", "REG-H73"],
        "substitution_options": [
            {
                "regimen_id": "REG-H71",
                "replace_drug": "metronidazole",
                "with_drug": "doxycycline",
                "target_condition": "infection",
                "expected_risk_delta": 0.81,
                "rationale": "reduces warfarin interaction burden",
            },
            {
                "regimen_id": "REG-H72",
                "replace_drug": "omeprazole",
                "with_drug": "pantoprazole",
                "target_condition": "gi_protection",
                "expected_risk_delta": 0.53,
                "rationale": "reduces antiplatelet interaction risk",
            },
            {
                "regimen_id": "REG-H73",
                "replace_drug": "diclofenac",
                "with_drug": "acetaminophen",
                "target_condition": "pain",
                "expected_risk_delta": 0.61,
                "rationale": "reduces additive bleeding risk",
            },
            {
                "regimen_id": "REG-H74",
                "replace_drug": "simvastatin",
                "with_drug": "pravastatin",
                "target_condition": "dyslipidemia",
                "expected_risk_delta": 0.34,
                "rationale": "lower CYP3A4-mediated interaction burden",
            },
        ],
    },
    {
        "case_id": "H-008",
        "template_family": "validation::borderline-moderate-hard-family",
        "split": "validation",
        "age": 79,
        "labs": {
            "egfr": 45.0,
            "creatinine": 1.5,
            "potassium": 4.8,
            "inr": 2.1,
            "alt": 112.0,
            "ast": 101.0,
        },
        "diagnoses": [
            "atrial_fibrillation",
            "heart_failure",
            "type_2_diabetes",
            "chronic_kidney_disease",
        ],
        "medications": [
            "apixaban",
            "clarithromycin",
            "digoxin",
            "verapamil",
            "spironolactone",
            "valsartan",
            "naproxen",
        ],
        "interactions": [
            {
                "interaction_id": "INT-H81",
                "drug_a": "apixaban",
                "drug_b": "clarithromycin",
                "severity": "major",
                "evidence": "increased anticoagulant exposure and bleeding risk",
            },
            {
                "interaction_id": "INT-H82",
                "drug_a": "digoxin",
                "drug_b": "verapamil",
                "severity": "moderate",
                "evidence": "P-gp inhibition can increase digoxin concentration",
            },
            {
                "interaction_id": "INT-H83",
                "drug_a": "spironolactone",
                "drug_b": "valsartan",
                "severity": "moderate",
                "evidence": "combined potassium retention near renal threshold",
            },
            {
                "interaction_id": "INT-H84",
                "drug_a": "apixaban",
                "drug_b": "naproxen",
                "severity": "major",
                "evidence": "substantial additive bleeding risk",
            },
        ],
        "required_regimens": ["REG-H81", "REG-H82", "REG-H83"],
        "substitution_options": [
            {
                "regimen_id": "REG-H81",
                "replace_drug": "clarithromycin",
                "with_drug": "azithromycin",
                "target_condition": "infection",
                "expected_risk_delta": 0.66,
                "rationale": "lower CYP3A4 interaction with apixaban",
            },
            {
                "regimen_id": "REG-H82",
                "replace_drug": "naproxen",
                "with_drug": "acetaminophen",
                "target_condition": "pain",
                "expected_risk_delta": 0.6,
                "rationale": "reduces additive bleeding risk",
            },
            {
                "regimen_id": "REG-H83",
                "replace_drug": "spironolactone",
                "with_drug": "eplerenone",
                "target_condition": "heart_failure",
                "expected_risk_delta": 0.52,
                "rationale": "lower hyperkalemia risk while preserving RAAS strategy",
            },
            {
                "regimen_id": "REG-H84",
                "replace_drug": "verapamil",
                "with_drug": "bisoprolol",
                "target_condition": "rate_control",
                "expected_risk_delta": 0.28,
                "rationale": "modest reduction in digoxin exposure risk",
            },
        ],
    },
    {
        "case_id": "H-009",
        "template_family": "train::renal-hepatic-tradeoff-hard",
        "split": "train",
        "age": 90,
        "labs": {
            "egfr": 25.0,
            "creatinine": 2.6,
            "potassium": 5.5,
            "inr": 2.7,
            "alt": 148.0,
            "ast": 139.0,
        },
        "diagnoses": [
            "atrial_fibrillation",
            "chronic_kidney_disease",
            "chronic_liver_disease",
            "coronary_artery_disease",
            "chronic_pain",
        ],
        "medications": [
            "warfarin",
            "metronidazole",
            "clopidogrel",
            "omeprazole",
            "spironolactone",
            "valsartan",
            "ibuprofen",
            "simvastatin",
            "diltiazem",
        ],
        "interactions": [
            {
                "interaction_id": "INT-H91",
                "drug_a": "warfarin",
                "drug_b": "metronidazole",
                "severity": "contraindicated",
                "evidence": "severe INR elevation and major bleeding risk",
            },
            {
                "interaction_id": "INT-H92",
                "drug_a": "clopidogrel",
                "drug_b": "omeprazole",
                "severity": "major",
                "evidence": "reduced antiplatelet activation",
            },
            {
                "interaction_id": "INT-H93",
                "drug_a": "spironolactone",
                "drug_b": "valsartan",
                "severity": "moderate",
                "evidence": "severe hyperkalemia risk in advanced CKD",
            },
            {
                "interaction_id": "INT-H94",
                "drug_a": "simvastatin",
                "drug_b": "diltiazem",
                "severity": "moderate",
                "evidence": "increased statin exposure with myopathy risk",
            },
            {
                "interaction_id": "INT-H95",
                "drug_a": "warfarin",
                "drug_b": "ibuprofen",
                "severity": "major",
                "evidence": "additive GI and systemic bleeding risk",
            },
        ],
        "required_regimens": ["REG-H91", "REG-H92", "REG-H93"],
        "substitution_options": [
            {
                "regimen_id": "REG-H91",
                "replace_drug": "metronidazole",
                "with_drug": "doxycycline",
                "target_condition": "infection",
                "expected_risk_delta": 0.83,
                "rationale": "reduces warfarin interaction burden",
            },
            {
                "regimen_id": "REG-H92",
                "replace_drug": "omeprazole",
                "with_drug": "pantoprazole",
                "target_condition": "gi_protection",
                "expected_risk_delta": 0.56,
                "rationale": "lowers antiplatelet interaction burden",
            },
            {
                "regimen_id": "REG-H93",
                "replace_drug": "ibuprofen",
                "with_drug": "acetaminophen",
                "target_condition": "pain",
                "expected_risk_delta": 0.62,
                "rationale": "reduces additive bleeding risk",
            },
            {
                "regimen_id": "REG-H94",
                "replace_drug": "simvastatin",
                "with_drug": "pravastatin",
                "target_condition": "dyslipidemia",
                "expected_risk_delta": 0.33,
                "rationale": "reduces CYP3A4 interaction burden",
            },
        ],
    },
    {
        "case_id": "H-010",
        "template_family": "validation::decision-boundary-substitution-hard",
        "split": "validation",
        "age": 84,
        "labs": {
            "egfr": 44.0,
            "creatinine": 1.8,
            "potassium": 5.1,
            "inr": 2.2,
            "alt": 122.0,
            "ast": 120.0,
        },
        "diagnoses": [
            "atrial_fibrillation",
            "heart_failure",
            "chronic_kidney_disease",
            "type_2_diabetes",
        ],
        "medications": [
            "apixaban",
            "clarithromycin",
            "digoxin",
            "verapamil",
            "spironolactone",
            "lisinopril",
            "naproxen",
        ],
        "interactions": [
            {
                "interaction_id": "INT-H101",
                "drug_a": "apixaban",
                "drug_b": "clarithromycin",
                "severity": "major",
                "evidence": "higher anticoagulant exposure and bleeding risk",
            },
            {
                "interaction_id": "INT-H102",
                "drug_a": "digoxin",
                "drug_b": "verapamil",
                "severity": "moderate",
                "evidence": "P-gp inhibition may increase digoxin concentration",
            },
            {
                "interaction_id": "INT-H103",
                "drug_a": "spironolactone",
                "drug_b": "lisinopril",
                "severity": "moderate",
                "evidence": "hyperkalemia risk near renal threshold",
            },
            {
                "interaction_id": "INT-H104",
                "drug_a": "apixaban",
                "drug_b": "naproxen",
                "severity": "major",
                "evidence": "additive anticoagulation-related bleeding risk",
            },
        ],
        "required_regimens": ["REG-H101", "REG-H102", "REG-H103"],
        "substitution_options": [
            {
                "regimen_id": "REG-H101",
                "replace_drug": "clarithromycin",
                "with_drug": "azithromycin",
                "target_condition": "infection",
                "expected_risk_delta": 0.68,
                "rationale": "reduces CYP3A4 interaction with apixaban",
            },
            {
                "regimen_id": "REG-H102",
                "replace_drug": "naproxen",
                "with_drug": "acetaminophen",
                "target_condition": "pain",
                "expected_risk_delta": 0.61,
                "rationale": "reduces additive bleeding risk",
            },
            {
                "regimen_id": "REG-H103",
                "replace_drug": "spironolactone",
                "with_drug": "eplerenone",
                "target_condition": "heart_failure",
                "expected_risk_delta": 0.53,
                "rationale": "reduces hyperkalemia exposure in CKD",
            },
            {
                "regimen_id": "REG-H104",
                "replace_drug": "verapamil",
                "with_drug": "bisoprolol",
                "target_condition": "rate_control",
                "expected_risk_delta": 0.29,
                "rationale": "modest reduction in digoxin interaction burden",
            },
        ],
    },
]
