"""Deterministic DDI cases for the medium task level."""

from typing import Any, Dict, List

from .validated_batch_01 import VALIDATED_MEDIUM_CASES

Case = Dict[str, Any]

MEDIUM_CASES: List[Case] = [
    {
        "case_id": "M-001",
        "age": 83,
        "labs": {"egfr": 31.0, "creatinine": 2.0, "potassium": 5.4, "inr": 2.1},
        "diagnoses": [
            "heart_failure",
            "atrial_fibrillation",
            "type_2_diabetes",
            "chronic_kidney_disease",
        ],
        "medications": [
            "warfarin",
            "amiodarone",
            "spironolactone",
            "lisinopril",
            "furosemide",
            "metformin",
            "insulin_glargine",
            "atorvastatin",
            "omeprazole",
            "sertraline",
            "trimethoprim_sulfamethoxazole",
        ],
        "interactions": [
            {
                "interaction_id": "INT-M1",
                "drug_a": "warfarin",
                "drug_b": "amiodarone",
                "severity": "major",
                "evidence": "CYP inhibition elevates warfarin exposure",
            },
            {
                "interaction_id": "INT-M2",
                "drug_a": "spironolactone",
                "drug_b": "lisinopril",
                "severity": "moderate",
                "evidence": "hyperkalemia risk with renal impairment",
            },
            {
                "interaction_id": "INT-M3",
                "drug_a": "metformin",
                "drug_b": "furosemide",
                "severity": "moderate",
                "evidence": "reduced renal clearance can increase lactic acidosis risk",
            },
            {
                "interaction_id": "INT-M4",
                "drug_a": "warfarin",
                "drug_b": "trimethoprim_sulfamethoxazole",
                "severity": "contraindicated",
                "evidence": "marked INR elevation and bleeding",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
    {
        "case_id": "M-002",
        "age": 81,
        "labs": {"egfr": 38.0, "creatinine": 1.8, "potassium": 5.1, "inr": 2.0},
        "diagnoses": [
            "heart_failure",
            "atrial_fibrillation",
            "type_2_diabetes",
            "chronic_kidney_disease",
            "osteoarthritis",
        ],
        "medications": [
            "digoxin",
            "amiodarone",
            "spironolactone",
            "losartan",
            "rivaroxaban",
            "naproxen",
            "glipizide",
            "ciprofloxacin",
        ],
        "interactions": [
            {
                "interaction_id": "INT-M21",
                "drug_a": "digoxin",
                "drug_b": "amiodarone",
                "severity": "major",
                "evidence": "P-gp inhibition raises digoxin concentration",
            },
            {
                "interaction_id": "INT-M22",
                "drug_a": "spironolactone",
                "drug_b": "losartan",
                "severity": "moderate",
                "evidence": "hyperkalemia risk increased in CKD",
            },
            {
                "interaction_id": "INT-M23",
                "drug_a": "rivaroxaban",
                "drug_b": "naproxen",
                "severity": "major",
                "evidence": "additive bleeding risk with anticoagulant and NSAID",
            },
            {
                "interaction_id": "INT-M24",
                "drug_a": "glipizide",
                "drug_b": "ciprofloxacin",
                "severity": "moderate",
                "evidence": "dysglycemia risk from fluoroquinolone-sulfonylurea combination",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
    {
        "case_id": "M-003",
        "age": 79,
        "labs": {"egfr": 44.0, "creatinine": 1.7, "potassium": 5.0, "inr": 2.0},
        "diagnoses": ["heart_failure", "chronic_kidney_disease", "atrial_fibrillation"],
        "medications": [
            "spironolactone",
            "lisinopril",
            "metformin",
            "furosemide",
            "warfarin",
            "fluconazole",
        ],
        "interactions": [
            {
                "interaction_id": "INT-M31",
                "drug_a": "spironolactone",
                "drug_b": "lisinopril",
                "severity": "moderate",
                "evidence": "hyperkalemia risk in CKD",
            },
            {
                "interaction_id": "INT-M32",
                "drug_a": "metformin",
                "drug_b": "furosemide",
                "severity": "moderate",
                "evidence": "renal stress may increase lactic acidosis risk",
            },
            {
                "interaction_id": "INT-M33",
                "drug_a": "warfarin",
                "drug_b": "fluconazole",
                "severity": "major",
                "evidence": "CYP inhibition increases anticoagulant effect",
            },
            {
                "interaction_id": "INT-M34",
                "drug_a": "furosemide",
                "drug_b": "warfarin",
                "severity": "minor",
                "evidence": "volume changes may alter INR stability",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
    {
        "case_id": "M-004",
        "age": 80,
        "labs": {"egfr": 52.0, "creatinine": 1.3, "potassium": 4.7, "inr": 2.2},
        "diagnoses": ["atrial_fibrillation", "hypertension", "heart_failure"],
        "medications": [
            "digoxin",
            "verapamil",
            "spironolactone",
            "losartan",
            "warfarin",
            "amiodarone",
        ],
        "interactions": [
            {
                "interaction_id": "INT-M41",
                "drug_a": "digoxin",
                "drug_b": "verapamil",
                "severity": "moderate",
                "evidence": "P-gp inhibition can raise digoxin concentration",
            },
            {
                "interaction_id": "INT-M42",
                "drug_a": "spironolactone",
                "drug_b": "losartan",
                "severity": "moderate",
                "evidence": "combined potassium retention",
            },
            {
                "interaction_id": "INT-M43",
                "drug_a": "warfarin",
                "drug_b": "amiodarone",
                "severity": "major",
                "evidence": "CYP interaction elevates warfarin effect",
            },
            {
                "interaction_id": "INT-M44",
                "drug_a": "verapamil",
                "drug_b": "losartan",
                "severity": "minor",
                "evidence": "possible additive hypotensive effect",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
    {
        "case_id": "M-005",
        "age": 76,
        "labs": {"egfr": 61.0, "creatinine": 1.1, "potassium": 4.4, "inr": 2.1},
        "diagnoses": ["type_2_diabetes", "atrial_fibrillation", "dyslipidemia"],
        "medications": [
            "glipizide",
            "ciprofloxacin",
            "warfarin",
            "trimethoprim_sulfamethoxazole",
            "simvastatin",
            "amlodipine",
        ],
        "interactions": [
            {
                "interaction_id": "INT-M51",
                "drug_a": "glipizide",
                "drug_b": "ciprofloxacin",
                "severity": "moderate",
                "evidence": "dysglycemia risk from fluoroquinolone-sulfonylurea pair",
            },
            {
                "interaction_id": "INT-M52",
                "drug_a": "warfarin",
                "drug_b": "trimethoprim_sulfamethoxazole",
                "severity": "contraindicated",
                "evidence": "marked INR elevation and bleeding risk",
            },
            {
                "interaction_id": "INT-M53",
                "drug_a": "simvastatin",
                "drug_b": "amlodipine",
                "severity": "moderate",
                "evidence": "higher statin exposure and myopathy risk",
            },
            {
                "interaction_id": "INT-M54",
                "drug_a": "amlodipine",
                "drug_b": "ciprofloxacin",
                "severity": "minor",
                "evidence": "possible additive hypotension in frail adults",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
    {
        "case_id": "M-006",
        "age": 86,
        "labs": {"egfr": 29.0, "creatinine": 2.2, "potassium": 5.3, "inr": 2.3},
        "diagnoses": ["chronic_kidney_disease", "heart_failure", "depression"],
        "medications": [
            "spironolactone",
            "valsartan",
            "sertraline",
            "aspirin",
            "warfarin",
            "metronidazole",
        ],
        "interactions": [
            {
                "interaction_id": "INT-M61",
                "drug_a": "spironolactone",
                "drug_b": "valsartan",
                "severity": "moderate",
                "evidence": "high hyperkalemia risk in advanced CKD",
            },
            {
                "interaction_id": "INT-M62",
                "drug_a": "sertraline",
                "drug_b": "aspirin",
                "severity": "minor",
                "evidence": "increased bleeding tendency, amplified in frailty",
            },
            {
                "interaction_id": "INT-M63",
                "drug_a": "warfarin",
                "drug_b": "metronidazole",
                "severity": "contraindicated",
                "evidence": "substantial INR increase and severe bleeding risk",
            },
            {
                "interaction_id": "INT-M64",
                "drug_a": "aspirin",
                "drug_b": "warfarin",
                "severity": "major",
                "evidence": "additive anticoagulation and bleeding",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
    {
        "case_id": "M-007",
        "template_family": "validation::borderline-monitor-family",
        "split": "validation",
        "age": 79,
        "labs": {
            "egfr": 45.0,
            "creatinine": 1.4,
            "potassium": 4.8,
            "inr": 2.2,
            "alt": 118.0,
            "ast": 109.0,
        },
        "diagnoses": [
            "chronic_kidney_disease",
            "heart_failure",
            "atrial_fibrillation",
            "nonalcoholic_steatohepatitis",
        ],
        "medications": [
            "spironolactone",
            "losartan",
            "metformin",
            "furosemide",
            "warfarin",
            "fluconazole",
        ],
        "interactions": [
            {
                "interaction_id": "INT-M71",
                "drug_a": "spironolactone",
                "drug_b": "losartan",
                "severity": "moderate",
                "evidence": "combined potassium retention risk",
            },
            {
                "interaction_id": "INT-M72",
                "drug_a": "metformin",
                "drug_b": "furosemide",
                "severity": "moderate",
                "evidence": "volume depletion may increase lactic acidosis risk",
            },
            {
                "interaction_id": "INT-M73",
                "drug_a": "warfarin",
                "drug_b": "fluconazole",
                "severity": "major",
                "evidence": "CYP inhibition can raise anticoagulant effect",
            },
            {
                "interaction_id": "INT-M74",
                "drug_a": "furosemide",
                "drug_b": "warfarin",
                "severity": "minor",
                "evidence": "fluid shifts may affect INR stability",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
    {
        "case_id": "M-008",
        "template_family": "validation::hepatic-escalation-family",
        "split": "validation",
        "age": 77,
        "labs": {
            "egfr": 52.0,
            "creatinine": 1.2,
            "potassium": 4.6,
            "inr": 1.9,
            "alt": 146.0,
            "ast": 133.0,
        },
        "diagnoses": [
            "atrial_fibrillation",
            "type_2_diabetes",
            "chronic_liver_disease",
            "hypertension",
        ],
        "medications": [
            "digoxin",
            "verapamil",
            "glipizide",
            "ciprofloxacin",
            "warfarin",
            "metronidazole",
        ],
        "interactions": [
            {
                "interaction_id": "INT-M81",
                "drug_a": "digoxin",
                "drug_b": "verapamil",
                "severity": "moderate",
                "evidence": "P-gp inhibition can elevate digoxin levels",
            },
            {
                "interaction_id": "INT-M82",
                "drug_a": "glipizide",
                "drug_b": "ciprofloxacin",
                "severity": "moderate",
                "evidence": "fluoroquinolone may destabilize glycemic control",
            },
            {
                "interaction_id": "INT-M83",
                "drug_a": "warfarin",
                "drug_b": "metronidazole",
                "severity": "contraindicated",
                "evidence": "severe INR increase and major bleeding risk",
            },
            {
                "interaction_id": "INT-M84",
                "drug_a": "verapamil",
                "drug_b": "ciprofloxacin",
                "severity": "minor",
                "evidence": "possible additive conduction slowing",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
    {
        "case_id": "M-009",
        "template_family": "train::decision-boundary-flip-medium",
        "split": "train",
        "age": 80,
        "labs": {
            "egfr": 44.0,
            "creatinine": 1.7,
            "potassium": 5.0,
            "inr": 2.0,
            "alt": 121.0,
            "ast": 124.0,
        },
        "diagnoses": [
            "atrial_fibrillation",
            "chronic_kidney_disease",
            "heart_failure",
            "chronic_liver_disease",
        ],
        "medications": [
            "digoxin",
            "verapamil",
            "spironolactone",
            "valsartan",
            "warfarin",
            "fluconazole",
        ],
        "interactions": [
            {
                "interaction_id": "INT-M91",
                "drug_a": "digoxin",
                "drug_b": "verapamil",
                "severity": "moderate",
                "evidence": "P-gp inhibition increases digoxin levels",
            },
            {
                "interaction_id": "INT-M92",
                "drug_a": "spironolactone",
                "drug_b": "valsartan",
                "severity": "moderate",
                "evidence": "hyperkalemia risk with renal impairment",
            },
            {
                "interaction_id": "INT-M93",
                "drug_a": "warfarin",
                "drug_b": "fluconazole",
                "severity": "major",
                "evidence": "CYP inhibition elevates anticoagulant effect",
            },
            {
                "interaction_id": "INT-M94",
                "drug_a": "valsartan",
                "drug_b": "fluconazole",
                "severity": "minor",
                "evidence": "possible additive hypotension in frailty",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
    {
        "case_id": "M-010",
        "template_family": "validation::comorbidity-bundle-medium",
        "split": "validation",
        "age": 86,
        "labs": {
            "egfr": 28.0,
            "creatinine": 2.3,
            "potassium": 5.4,
            "inr": 2.5,
            "alt": 94.0,
            "ast": 88.0,
        },
        "diagnoses": [
            "chronic_kidney_disease",
            "heart_failure",
            "atrial_fibrillation",
            "type_2_diabetes",
        ],
        "medications": [
            "warfarin",
            "metronidazole",
            "spironolactone",
            "lisinopril",
            "metformin",
            "furosemide",
        ],
        "interactions": [
            {
                "interaction_id": "INT-M101",
                "drug_a": "warfarin",
                "drug_b": "metronidazole",
                "severity": "contraindicated",
                "evidence": "marked INR elevation and severe bleeding risk",
            },
            {
                "interaction_id": "INT-M102",
                "drug_a": "spironolactone",
                "drug_b": "lisinopril",
                "severity": "moderate",
                "evidence": "high hyperkalemia risk in advanced CKD",
            },
            {
                "interaction_id": "INT-M103",
                "drug_a": "metformin",
                "drug_b": "furosemide",
                "severity": "moderate",
                "evidence": "renal stress may increase lactic acidosis risk",
            },
            {
                "interaction_id": "INT-M104",
                "drug_a": "furosemide",
                "drug_b": "warfarin",
                "severity": "minor",
                "evidence": "volume shifts can destabilize INR",
            },
        ],
        "required_regimens": [],
        "substitution_options": [],
    },
]


def _generate_medium_expansion(count: int = 100, start_idx: int = 300) -> List[Case]:
    generated: List[Case] = []
    for offset in range(count):
        idx = start_idx + offset
        split = "validation" if offset % 5 == 4 else "train"
        template_family = f"{split}::bulk-medium-{idx}"
        case_id = f"M-{idx}"
        interaction_prefix = f"INT-M{idx}"

        generated.append(
            {
                "case_id": case_id,
                "template_family": template_family,
                "split": split,
                "age": 74 + (offset % 15),
                "labs": {
                    "egfr": float(30 + (offset % 20)),
                    "creatinine": round(1.2 + (offset % 10) * 0.12, 2),
                    "potassium": round(4.5 + (offset % 7) * 0.13, 2),
                    "inr": round(1.9 + (offset % 6) * 0.16, 2),
                    "alt": float(88 + (offset % 6) * 11),
                    "ast": float(85 + (offset % 6) * 10),
                },
                "diagnoses": [
                    "atrial_fibrillation",
                    "heart_failure",
                    "chronic_kidney_disease",
                    "type_2_diabetes" if offset % 2 == 0 else "hypertension",
                ],
                "medications": [
                    "warfarin",
                    "metronidazole",
                    "spironolactone",
                    "lisinopril",
                    "metformin",
                    "furosemide",
                    "digoxin" if offset % 2 == 0 else "verapamil",
                ],
                "interactions": [
                    {
                        "interaction_id": f"{interaction_prefix}1",
                        "drug_a": "warfarin",
                        "drug_b": "metronidazole",
                        "severity": "contraindicated",
                        "evidence": "marked INR elevation and severe bleeding risk",
                    },
                    {
                        "interaction_id": f"{interaction_prefix}2",
                        "drug_a": "spironolactone",
                        "drug_b": "lisinopril",
                        "severity": "moderate",
                        "evidence": "high hyperkalemia risk in CKD",
                    },
                    {
                        "interaction_id": f"{interaction_prefix}3",
                        "drug_a": "metformin",
                        "drug_b": "furosemide",
                        "severity": "moderate",
                        "evidence": "renal stress may increase lactic acidosis risk",
                    },
                    {
                        "interaction_id": f"{interaction_prefix}4",
                        "drug_a": "digoxin" if offset % 2 == 0 else "verapamil",
                        "drug_b": "furosemide",
                        "severity": "minor",
                        "evidence": "possible volume-related conduction intolerance in frailty",
                    },
                ],
                "required_regimens": [],
                "substitution_options": [],
            }
        )
    return generated


MEDIUM_CASES.extend(_generate_medium_expansion())
MEDIUM_CASES.extend(VALIDATED_MEDIUM_CASES)
