"""Validated synthetic batch 01 cases merged into task pools."""

from typing import Any, Dict, List

Case = Dict[str, Any]

VALIDATED_EASY_CASES: List[Case] = [{'case_id': 'E_11',
  'template_family': 'train::elderly-polypharmacy-001',
  'split': 'train',
  'age': 82,
  'labs': {'egfr': 52, 'creatinine': 1.3, 'potassium': 4.8, 'inr': 2.9},
  'diagnoses': ['atrial fibrillation', 'hypertension'],
  'medications': ['warfarin', 'amiodarone', 'lisinopril', 'spironolactone'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'warfarin',
                    'drug_b': 'amiodarone',
                    'severity': 'major',
                    'evidence': 'Amiodarone inhibits CYP2C9 increasing warfarin levels and INR'},
                   {'interaction_id': 'i2',
                    'drug_a': 'lisinopril',
                    'drug_b': 'spironolactone',
                    'severity': 'major',
                    'evidence': 'Dual RAAS blockade increases risk of hyperkalemia'},
                   {'interaction_id': 'i3',
                    'drug_a': 'amiodarone',
                    'drug_b': 'spironolactone',
                    'severity': 'moderate',
                    'evidence': 'Both prolong QT interval increasing arrhythmia risk'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_12',
  'template_family': 'train::renal-diabetes-001',
  'split': 'train',
  'age': 76,
  'labs': {'egfr': 44, 'creatinine': 1.6, 'potassium': 5.1, 'inr': 1.1},
  'diagnoses': ['type 2 diabetes', 'ckd'],
  'medications': ['metformin', 'glyburide', 'lisinopril', 'ibuprofen'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'metformin',
                    'drug_b': 'ibuprofen',
                    'severity': 'moderate',
                    'evidence': 'NSAIDs reduce renal perfusion increasing metformin accumulation '
                                'risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'glyburide',
                    'drug_b': 'ibuprofen',
                    'severity': 'moderate',
                    'evidence': 'NSAIDs may potentiate hypoglycemia via protein binding '
                                'displacement'},
                   {'interaction_id': 'i3',
                    'drug_a': 'lisinopril',
                    'drug_b': 'ibuprofen',
                    'severity': 'major',
                    'evidence': 'ACE inhibitors with NSAIDs increase risk of acute kidney injury'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_13',
  'template_family': 'validation::hepatic-statin-001',
  'split': 'validation',
  'age': 68,
  'labs': {'egfr': 70, 'creatinine': 1, 'potassium': 4.3, 'inr': 1, 'alt': 85, 'ast': 72},
  'diagnoses': ['hyperlipidemia', 'hypertension'],
  'medications': ['simvastatin', 'clarithromycin', 'aspirin', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'simvastatin',
                    'drug_b': 'clarithromycin',
                    'severity': 'contraindicated',
                    'evidence': 'Clarithromycin inhibits CYP3A4 causing marked statin accumulation '
                                'and rhabdomyolysis'},
                   {'interaction_id': 'i2',
                    'drug_a': 'aspirin',
                    'drug_b': 'clarithromycin',
                    'severity': 'minor',
                    'evidence': 'Additive GI irritation risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'simvastatin',
                    'drug_b': 'aspirin',
                    'severity': 'minor',
                    'evidence': 'Minimal interaction but additive hepatic stress possible'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_14',
  'template_family': 'train::af-anticoag-001',
  'split': 'train',
  'age': 79,
  'labs': {'egfr': 60, 'creatinine': 1.2, 'potassium': 4.4, 'inr': 3.2},
  'diagnoses': ['atrial fibrillation', 'hypertension'],
  'medications': ['warfarin', 'trimethoprim-sulfamethoxazole', 'metoprolol', 'furosemide'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'warfarin',
                    'drug_b': 'trimethoprim-sulfamethoxazole',
                    'severity': 'major',
                    'evidence': 'TMP-SMX inhibits warfarin metabolism increasing INR'},
                   {'interaction_id': 'i2',
                    'drug_a': 'metoprolol',
                    'drug_b': 'trimethoprim-sulfamethoxazole',
                    'severity': 'moderate',
                    'evidence': 'CYP2D6 inhibition increases beta blocker levels'},
                   {'interaction_id': 'i3',
                    'drug_a': 'warfarin',
                    'drug_b': 'metoprolol',
                    'severity': 'minor',
                    'evidence': 'No major PK interaction; fall risk indirectly increases bleeding '
                                'risk'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_15',
  'template_family': 'train::heart-failure-001',
  'split': 'train',
  'age': 83,
  'labs': {'egfr': 48, 'creatinine': 1.5, 'potassium': 5.3, 'inr': 1.2},
  'diagnoses': ['heart failure', 'hypertension'],
  'medications': ['digoxin', 'furosemide', 'amiodarone', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'digoxin',
                    'drug_b': 'amiodarone',
                    'severity': 'major',
                    'evidence': 'Amiodarone increases digoxin levels via P-gp inhibition'},
                   {'interaction_id': 'i2',
                    'drug_a': 'furosemide',
                    'drug_b': 'digoxin',
                    'severity': 'major',
                    'evidence': 'Electrolyte imbalance increases digoxin toxicity risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'furosemide',
                    'drug_b': 'amiodarone',
                    'severity': 'moderate',
                    'evidence': 'Electrolyte shifts may potentiate QT prolongation'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_16',
  'template_family': 'validation::antibiotic-qt-001',
  'split': 'validation',
  'age': 74,
  'labs': {'egfr': 66, 'creatinine': 1.1, 'potassium': 3.6, 'inr': 1},
  'diagnoses': ['pneumonia', 'hypertension'],
  'medications': ['levofloxacin', 'amiodarone', 'ondansetron', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'levofloxacin',
                    'drug_b': 'amiodarone',
                    'severity': 'major',
                    'evidence': 'Additive QT prolongation increases torsades risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'ondansetron',
                    'drug_b': 'amiodarone',
                    'severity': 'major',
                    'evidence': 'QT prolongation risk significantly increased'},
                   {'interaction_id': 'i3',
                    'drug_a': 'levofloxacin',
                    'drug_b': 'ondansetron',
                    'severity': 'moderate',
                    'evidence': 'Combined QT prolongation effect'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_17',
  'template_family': 'train::pain-nsaid-001',
  'split': 'train',
  'age': 70,
  'labs': {'egfr': 55, 'creatinine': 1.3, 'potassium': 4.9, 'inr': 2.5},
  'diagnoses': ['arthritis', 'atrial fibrillation'],
  'medications': ['warfarin', 'naproxen', 'lisinopril', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'warfarin',
                    'drug_b': 'naproxen',
                    'severity': 'major',
                    'evidence': 'NSAIDs increase bleeding risk with anticoagulants'},
                   {'interaction_id': 'i2',
                    'drug_a': 'naproxen',
                    'drug_b': 'lisinopril',
                    'severity': 'moderate',
                    'evidence': 'NSAIDs reduce ACE inhibitor efficacy'},
                   {'interaction_id': 'i3',
                    'drug_a': 'warfarin',
                    'drug_b': 'lisinopril',
                    'severity': 'minor',
                    'evidence': 'Minimal direct interaction'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_18',
  'template_family': 'train::gout-renal-001',
  'split': 'train',
  'age': 72,
  'labs': {'egfr': 46, 'creatinine': 1.6, 'potassium': 4.7, 'inr': 1},
  'diagnoses': ['gout', 'hypertension'],
  'medications': ['colchicine', 'clarithromycin', 'atorvastatin', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'colchicine',
                    'drug_b': 'clarithromycin',
                    'severity': 'contraindicated',
                    'evidence': 'Strong CYP3A4 inhibition increases colchicine toxicity risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'atorvastatin',
                    'drug_b': 'clarithromycin',
                    'severity': 'major',
                    'evidence': 'Increased statin levels raise myopathy risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'colchicine',
                    'drug_b': 'atorvastatin',
                    'severity': 'moderate',
                    'evidence': 'Additive myotoxicity risk'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_19',
  'template_family': 'validation::bleeding-risk-001',
  'split': 'validation',
  'age': 81,
  'labs': {'egfr': 58, 'creatinine': 1.2, 'potassium': 4.5, 'inr': 3},
  'diagnoses': ['atrial fibrillation', 'hypertension'],
  'medications': ['warfarin', 'aspirin', 'clopidogrel', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'warfarin',
                    'drug_b': 'aspirin',
                    'severity': 'major',
                    'evidence': 'Additive anticoagulant and antiplatelet effect increases bleeding '
                                'risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'warfarin',
                    'drug_b': 'clopidogrel',
                    'severity': 'major',
                    'evidence': 'Combined therapy increases hemorrhage risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'aspirin',
                    'drug_b': 'clopidogrel',
                    'severity': 'moderate',
                    'evidence': 'Dual antiplatelet therapy increases bleeding risk'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_20',
  'template_family': 'train::seizure-enzyme-001',
  'split': 'train',
  'age': 65,
  'labs': {'egfr': 72, 'creatinine': 1, 'potassium': 4.2, 'inr': 1},
  'diagnoses': ['epilepsy', 'hypertension'],
  'medications': ['phenytoin', 'warfarin', 'omeprazole', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'phenytoin',
                    'drug_b': 'warfarin',
                    'severity': 'major',
                    'evidence': 'Phenytoin induces metabolism altering warfarin anticoagulation '
                                'unpredictably'},
                   {'interaction_id': 'i2',
                    'drug_a': 'phenytoin',
                    'drug_b': 'omeprazole',
                    'severity': 'moderate',
                    'evidence': 'Omeprazole may increase phenytoin levels'},
                   {'interaction_id': 'i3',
                    'drug_a': 'warfarin',
                    'drug_b': 'omeprazole',
                    'severity': 'minor',
                    'evidence': 'Slight CYP interaction possible'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_21',
  'template_family': 'train::copd-infection-001',
  'split': 'train',
  'age': 77,
  'labs': {'egfr': 63, 'creatinine': 1.1, 'potassium': 4, 'inr': 1},
  'diagnoses': ['copd', 'hypertension'],
  'medications': ['theophylline', 'ciprofloxacin', 'prednisone', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'theophylline',
                    'drug_b': 'ciprofloxacin',
                    'severity': 'major',
                    'evidence': 'Ciprofloxacin inhibits metabolism increasing theophylline '
                                'toxicity'},
                   {'interaction_id': 'i2',
                    'drug_a': 'prednisone',
                    'drug_b': 'ciprofloxacin',
                    'severity': 'moderate',
                    'evidence': 'Increased tendon rupture risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'theophylline',
                    'drug_b': 'prednisone',
                    'severity': 'minor',
                    'evidence': 'Minimal direct interaction'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_22',
  'template_family': 'validation::thyroid-cardiac-001',
  'split': 'validation',
  'age': 69,
  'labs': {'egfr': 68, 'creatinine': 1.1, 'potassium': 4.1, 'inr': 1},
  'diagnoses': ['hypothyroidism', 'arrhythmia'],
  'medications': ['levothyroxine', 'amiodarone', 'warfarin', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'amiodarone',
                    'drug_b': 'levothyroxine',
                    'severity': 'moderate',
                    'evidence': 'Amiodarone alters thyroid hormone metabolism'},
                   {'interaction_id': 'i2',
                    'drug_a': 'amiodarone',
                    'drug_b': 'warfarin',
                    'severity': 'major',
                    'evidence': 'Increased INR due to CYP inhibition'},
                   {'interaction_id': 'i3',
                    'drug_a': 'levothyroxine',
                    'drug_b': 'warfarin',
                    'severity': 'moderate',
                    'evidence': 'Thyroid hormone increases warfarin sensitivity'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_23',
  'template_family': 'train::ulcer-bleed-001',
  'split': 'train',
  'age': 75,
  'labs': {'egfr': 59, 'creatinine': 1.2, 'potassium': 4.3, 'inr': 2.7},
  'diagnoses': ['peptic ulcer', 'hypertension'],
  'medications': ['warfarin', 'ibuprofen', 'prednisone', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'warfarin',
                    'drug_b': 'ibuprofen',
                    'severity': 'major',
                    'evidence': 'High bleeding risk due to anticoagulant and NSAID'},
                   {'interaction_id': 'i2',
                    'drug_a': 'ibuprofen',
                    'drug_b': 'prednisone',
                    'severity': 'major',
                    'evidence': 'Increased GI ulceration risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'warfarin',
                    'drug_b': 'prednisone',
                    'severity': 'moderate',
                    'evidence': 'Steroids may increase bleeding tendency'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_24',
  'template_family': 'train::hiv-polypharmacy-001',
  'split': 'train',
  'age': 67,
  'labs': {'egfr': 64, 'creatinine': 1.1, 'potassium': 4.2, 'inr': 1.1},
  'diagnoses': ['hiv', 'hypertension'],
  'medications': ['ritonavir', 'simvastatin', 'clopidogrel', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'ritonavir',
                    'drug_b': 'simvastatin',
                    'severity': 'contraindicated',
                    'evidence': 'Strong CYP3A4 inhibition causes severe statin toxicity'},
                   {'interaction_id': 'i2',
                    'drug_a': 'ritonavir',
                    'drug_b': 'clopidogrel',
                    'severity': 'major',
                    'evidence': 'Reduces clopidogrel activation'},
                   {'interaction_id': 'i3',
                    'drug_a': 'simvastatin',
                    'drug_b': 'clopidogrel',
                    'severity': 'minor',
                    'evidence': 'Minimal interaction'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_25',
  'template_family': 'validation::psych-qt-001',
  'split': 'validation',
  'age': 71,
  'labs': {'egfr': 61, 'creatinine': 1.2, 'potassium': 3.7, 'inr': 1},
  'diagnoses': ['depression', 'hypertension'],
  'medications': ['citalopram', 'haloperidol', 'ondansetron', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'citalopram',
                    'drug_b': 'haloperidol',
                    'severity': 'major',
                    'evidence': 'Additive QT prolongation risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'haloperidol',
                    'drug_b': 'ondansetron',
                    'severity': 'major',
                    'evidence': 'High torsades risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'citalopram',
                    'drug_b': 'ondansetron',
                    'severity': 'moderate',
                    'evidence': 'Combined QT prolongation'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_26',
  'template_family': 'train::transplant-immune-001',
  'split': 'train',
  'age': 73,
  'labs': {'egfr': 50, 'creatinine': 1.4, 'potassium': 4.6, 'inr': 1.1},
  'diagnoses': ['transplant', 'hypertension'],
  'medications': ['tacrolimus', 'clarithromycin', 'prednisone', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'tacrolimus',
                    'drug_b': 'clarithromycin',
                    'severity': 'major',
                    'evidence': 'CYP3A4 inhibition increases tacrolimus toxicity'},
                   {'interaction_id': 'i2',
                    'drug_a': 'tacrolimus',
                    'drug_b': 'prednisone',
                    'severity': 'moderate',
                    'evidence': 'Additive immunosuppression'},
                   {'interaction_id': 'i3',
                    'drug_a': 'clarithromycin',
                    'drug_b': 'prednisone',
                    'severity': 'minor',
                    'evidence': 'Minimal interaction'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_27',
  'template_family': 'train::asthma-antibiotic-001',
  'split': 'train',
  'age': 66,
  'labs': {'egfr': 67, 'creatinine': 1, 'potassium': 4.1, 'inr': 1},
  'diagnoses': ['asthma', 'hypertension'],
  'medications': ['theophylline', 'erythromycin', 'albuterol', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'theophylline',
                    'drug_b': 'erythromycin',
                    'severity': 'major',
                    'evidence': 'Erythromycin inhibits metabolism of theophylline'},
                   {'interaction_id': 'i2',
                    'drug_a': 'erythromycin',
                    'drug_b': 'albuterol',
                    'severity': 'moderate',
                    'evidence': 'QT prolongation risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'theophylline',
                    'drug_b': 'albuterol',
                    'severity': 'moderate',
                    'evidence': 'Additive CNS stimulation'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_28',
  'template_family': 'validation::geriatric-falls-001',
  'split': 'validation',
  'age': 88,
  'labs': {'egfr': 47, 'creatinine': 1.5, 'potassium': 4.8, 'inr': 2.6},
  'diagnoses': ['insomnia', 'af'],
  'medications': ['warfarin', 'zolpidem', 'lorazepam', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'zolpidem',
                    'drug_b': 'lorazepam',
                    'severity': 'major',
                    'evidence': 'Additive CNS depression increases fall risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'warfarin',
                    'drug_b': 'zolpidem',
                    'severity': 'minor',
                    'evidence': 'Indirect bleeding risk via falls'},
                   {'interaction_id': 'i3',
                    'drug_a': 'warfarin',
                    'drug_b': 'lorazepam',
                    'severity': 'minor',
                    'evidence': 'Minimal PK interaction'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_29',
  'template_family': 'train::ckd-hyperkalemia-001',
  'split': 'train',
  'age': 80,
  'labs': {'egfr': 42, 'creatinine': 1.8, 'potassium': 5.5, 'inr': 1},
  'diagnoses': ['ckd', 'hypertension'],
  'medications': ['lisinopril', 'spironolactone', 'trimethoprim', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'lisinopril',
                    'drug_b': 'spironolactone',
                    'severity': 'major',
                    'evidence': 'Severe hyperkalemia risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'trimethoprim',
                    'drug_b': 'spironolactone',
                    'severity': 'major',
                    'evidence': 'Trimethoprim acts like potassium-sparing diuretic'},
                   {'interaction_id': 'i3',
                    'drug_a': 'lisinopril',
                    'drug_b': 'trimethoprim',
                    'severity': 'moderate',
                    'evidence': 'Additive hyperkalemia risk'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'E_30',
  'template_family': 'validation::liver-polypharmacy-001',
  'split': 'validation',
  'age': 73,
  'labs': {'egfr': 65, 'creatinine': 1.1, 'potassium': 4.2, 'inr': 1.2, 'alt': 92, 'ast': 88},
  'diagnoses': ['hepatitis', 'hypertension'],
  'medications': ['acetaminophen', 'isoniazid', 'rifampin', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'acetaminophen',
                    'drug_b': 'isoniazid',
                    'severity': 'major',
                    'evidence': 'Increased hepatotoxicity risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'isoniazid',
                    'drug_b': 'rifampin',
                    'severity': 'major',
                    'evidence': 'Combined hepatotoxicity risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'acetaminophen',
                    'drug_b': 'rifampin',
                    'severity': 'moderate',
                    'evidence': 'Enzyme induction increases toxic metabolites'}],
  'required_regimens': [],
  'substitution_options': []}]

VALIDATED_MEDIUM_CASES: List[Case] = [{'case_id': 'M_11',
  'template_family': 'train::af-ckd-boundary-001',
  'split': 'train',
  'age': 84,
  'labs': {'egfr': 46, 'creatinine': 1.6, 'potassium': 4.9, 'inr': 2.7},
  'diagnoses': ['atrial fibrillation', 'ckd'],
  'medications': ['apixaban', 'amiodarone', 'diltiazem', 'atorvastatin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'apixaban',
                    'drug_b': 'amiodarone',
                    'severity': 'moderate',
                    'evidence': 'P-gp inhibition may increase apixaban levels in elderly CKD'},
                   {'interaction_id': 'i2',
                    'drug_a': 'apixaban',
                    'drug_b': 'diltiazem',
                    'severity': 'moderate',
                    'evidence': 'CYP3A4 inhibition increases anticoagulant exposure'},
                   {'interaction_id': 'i3',
                    'drug_a': 'amiodarone',
                    'drug_b': 'diltiazem',
                    'severity': 'major',
                    'evidence': 'Additive bradycardia and AV block risk'},
                   {'interaction_id': 'i4',
                    'drug_a': 'atorvastatin',
                    'drug_b': 'diltiazem',
                    'severity': 'moderate',
                    'evidence': 'CYP3A4 inhibition increases statin levels'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_12',
  'template_family': 'validation::diabetes-renal-flip-001',
  'split': 'validation',
  'age': 79,
  'labs': {'egfr': 45, 'creatinine': 1.7, 'potassium': 5, 'inr': 1},
  'diagnoses': ['type 2 diabetes', 'ckd'],
  'medications': ['metformin', 'empagliflozin', 'lisinopril', 'furosemide'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'metformin',
                    'drug_b': 'empagliflozin',
                    'severity': 'major',
                    'evidence': 'Volume depletion may increase lactic acidosis risk near eGFR '
                                'threshold; elevated clinical risk requiring escalation'},
                   {'interaction_id': 'i2',
                    'drug_a': 'empagliflozin',
                    'drug_b': 'furosemide',
                    'severity': 'moderate',
                    'evidence': 'Additive diuresis increases dehydration risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'lisinopril',
                    'drug_b': 'furosemide',
                    'severity': 'moderate',
                    'evidence': 'Hypotension risk increased in elderly'},
                   {'interaction_id': 'i4',
                    'drug_a': 'lisinopril',
                    'drug_b': 'empagliflozin',
                    'severity': 'moderate',
                    'evidence': 'Combined renal perfusion effects in CKD'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_13',
  'template_family': 'train::hepatic-threshold-002',
  'split': 'train',
  'age': 72,
  'labs': {'egfr': 68, 'creatinine': 1.1, 'potassium': 4.3, 'inr': 1.1, 'alt': 110, 'ast': 95},
  'diagnoses': ['hyperlipidemia', 'hypertension'],
  'medications': ['atorvastatin', 'fluconazole', 'warfarin', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'atorvastatin',
                    'drug_b': 'fluconazole',
                    'severity': 'major',
                    'evidence': 'CYP3A4 inhibition increases statin toxicity risk in hepatic '
                                'impairment'},
                   {'interaction_id': 'i2',
                    'drug_a': 'warfarin',
                    'drug_b': 'fluconazole',
                    'severity': 'major',
                    'evidence': 'Fluconazole inhibits warfarin metabolism increasing INR'},
                   {'interaction_id': 'i3',
                    'drug_a': 'warfarin',
                    'drug_b': 'atorvastatin',
                    'severity': 'moderate',
                    'evidence': 'Protein binding displacement may increase bleeding risk'},
                   {'interaction_id': 'i4',
                    'drug_a': 'atorvastatin',
                    'drug_b': 'warfarin',
                    'severity': 'moderate',
                    'evidence': 'Altered anticoagulation in hepatic dysfunction'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_14',
  'template_family': 'validation::qt-risk-bundle-002',
  'split': 'validation',
  'age': 83,
  'labs': {'egfr': 58, 'creatinine': 1.3, 'potassium': 3.5, 'inr': 1},
  'diagnoses': ['nausea', 'arrhythmia'],
  'medications': ['ondansetron', 'amiodarone', 'azithromycin', 'citalopram'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'ondansetron',
                    'drug_b': 'amiodarone',
                    'severity': 'major',
                    'evidence': 'High torsades risk due to QT prolongation'},
                   {'interaction_id': 'i2',
                    'drug_a': 'azithromycin',
                    'drug_b': 'amiodarone',
                    'severity': 'major',
                    'evidence': 'Additive QT prolongation'},
                   {'interaction_id': 'i3',
                    'drug_a': 'citalopram',
                    'drug_b': 'ondansetron',
                    'severity': 'moderate',
                    'evidence': 'QT prolongation risk increases with electrolyte imbalance'},
                   {'interaction_id': 'i4',
                    'drug_a': 'citalopram',
                    'drug_b': 'azithromycin',
                    'severity': 'moderate',
                    'evidence': 'Combined QT effects in elderly'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_15',
  'template_family': 'train::hf-diuretic-balance-001',
  'split': 'train',
  'age': 86,
  'labs': {'egfr': 47, 'creatinine': 1.5, 'potassium': 5.2, 'inr': 1.1},
  'diagnoses': ['heart failure', 'hypertension'],
  'medications': ['spironolactone', 'furosemide', 'lisinopril', 'digoxin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'spironolactone',
                    'drug_b': 'lisinopril',
                    'severity': 'major',
                    'evidence': 'Hyperkalemia risk amplified in CKD elderly'},
                   {'interaction_id': 'i2',
                    'drug_a': 'furosemide',
                    'drug_b': 'digoxin',
                    'severity': 'major',
                    'evidence': 'Electrolyte imbalance increases digoxin toxicity'},
                   {'interaction_id': 'i3',
                    'drug_a': 'digoxin',
                    'drug_b': 'spironolactone',
                    'severity': 'moderate',
                    'evidence': 'Spironolactone may increase digoxin levels'},
                   {'interaction_id': 'i4',
                    'drug_a': 'furosemide',
                    'drug_b': 'lisinopril',
                    'severity': 'moderate',
                    'evidence': 'Hypotension risk in volume depletion'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_16',
  'template_family': 'train::antibiotic-anticoag-002',
  'split': 'train',
  'age': 78,
  'labs': {'egfr': 55, 'creatinine': 1.3, 'potassium': 4.4, 'inr': 3.1},
  'diagnoses': ['af', 'infection'],
  'medications': ['warfarin', 'levofloxacin', 'prednisone', 'omeprazole'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'warfarin',
                    'drug_b': 'levofloxacin',
                    'severity': 'major',
                    'evidence': 'Fluoroquinolones increase INR via gut flora suppression'},
                   {'interaction_id': 'i2',
                    'drug_a': 'prednisone',
                    'drug_b': 'levofloxacin',
                    'severity': 'moderate',
                    'evidence': 'Increased tendon rupture risk in elderly'},
                   {'interaction_id': 'i3',
                    'drug_a': 'warfarin',
                    'drug_b': 'prednisone',
                    'severity': 'moderate',
                    'evidence': 'Steroids may enhance bleeding tendency'},
                   {'interaction_id': 'i4',
                    'drug_a': 'omeprazole',
                    'drug_b': 'warfarin',
                    'severity': 'moderate',
                    'evidence': 'CYP2C19 inhibition may alter INR'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_17',
  'template_family': 'validation::ckd-hyperkalemia-002',
  'split': 'validation',
  'age': 82,
  'labs': {'egfr': 43, 'creatinine': 1.9, 'potassium': 5.4, 'inr': 1},
  'diagnoses': ['ckd', 'hypertension'],
  'medications': ['losartan', 'spironolactone', 'trimethoprim', 'ibuprofen'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'losartan',
                    'drug_b': 'spironolactone',
                    'severity': 'major',
                    'evidence': 'Dual RAAS blockade increases hyperkalemia risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'spironolactone',
                    'drug_b': 'trimethoprim',
                    'severity': 'major',
                    'evidence': 'Trimethoprim acts as potassium-sparing agent'},
                   {'interaction_id': 'i3',
                    'drug_a': 'ibuprofen',
                    'drug_b': 'losartan',
                    'severity': 'moderate',
                    'evidence': 'NSAIDs reduce renal perfusion worsening CKD'},
                   {'interaction_id': 'i4',
                    'drug_a': 'ibuprofen',
                    'drug_b': 'spironolactone',
                    'severity': 'moderate',
                    'evidence': 'Renal impairment increases potassium retention'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_18',
  'template_family': 'train::psych-serotonin-001',
  'split': 'train',
  'age': 74,
  'labs': {'egfr': 62, 'creatinine': 1.1, 'potassium': 4, 'inr': 1},
  'diagnoses': ['depression', 'pain'],
  'medications': ['sertraline', 'tramadol', 'linezolid', 'ondansetron'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'sertraline',
                    'drug_b': 'linezolid',
                    'severity': 'major',
                    'evidence': 'Risk of serotonin syndrome'},
                   {'interaction_id': 'i2',
                    'drug_a': 'tramadol',
                    'drug_b': 'sertraline',
                    'severity': 'major',
                    'evidence': 'Increased serotonin syndrome risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'linezolid',
                    'drug_b': 'tramadol',
                    'severity': 'major',
                    'evidence': 'Additive serotonergic toxicity'},
                   {'interaction_id': 'i4',
                    'drug_a': 'ondansetron',
                    'drug_b': 'sertraline',
                    'severity': 'moderate',
                    'evidence': 'QT prolongation risk'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_19',
  'template_family': 'train::lipid-polypharmacy-002',
  'split': 'train',
  'age': 69,
  'labs': {'egfr': 71, 'creatinine': 1, 'potassium': 4.2, 'inr': 1},
  'diagnoses': ['hyperlipidemia', 'hypertension'],
  'medications': ['simvastatin', 'gemfibrozil', 'clarithromycin', 'warfarin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'simvastatin',
                    'drug_b': 'gemfibrozil',
                    'severity': 'contraindicated',
                    'evidence': 'High rhabdomyolysis risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'simvastatin',
                    'drug_b': 'clarithromycin',
                    'severity': 'contraindicated',
                    'evidence': 'CYP3A4 inhibition raises statin levels significantly'},
                   {'interaction_id': 'i3',
                    'drug_a': 'clarithromycin',
                    'drug_b': 'warfarin',
                    'severity': 'major',
                    'evidence': 'Increases INR'},
                   {'interaction_id': 'i4',
                    'drug_a': 'gemfibrozil',
                    'drug_b': 'warfarin',
                    'severity': 'moderate',
                    'evidence': 'Protein binding displacement'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_20',
  'template_family': 'validation::copd-infection-002',
  'split': 'validation',
  'age': 81,
  'labs': {'egfr': 57, 'creatinine': 1.2, 'potassium': 3.8, 'inr': 1},
  'diagnoses': ['copd', 'hypertension'],
  'medications': ['theophylline', 'ciprofloxacin', 'prednisone', 'salbutamol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'theophylline',
                    'drug_b': 'ciprofloxacin',
                    'severity': 'major',
                    'evidence': 'CYP inhibition increases toxicity'},
                   {'interaction_id': 'i2',
                    'drug_a': 'ciprofloxacin',
                    'drug_b': 'prednisone',
                    'severity': 'moderate',
                    'evidence': 'Tendon rupture risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'theophylline',
                    'drug_b': 'salbutamol',
                    'severity': 'moderate',
                    'evidence': 'Additive CNS stimulation'},
                   {'interaction_id': 'i4',
                    'drug_a': 'prednisone',
                    'drug_b': 'salbutamol',
                    'severity': 'minor',
                    'evidence': 'Minimal interaction'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_21',
  'template_family': 'train::thyroid-cardiac-002',
  'split': 'train',
  'age': 75,
  'labs': {'egfr': 64, 'creatinine': 1.1, 'potassium': 4.3, 'inr': 1.1},
  'diagnoses': ['hypothyroidism', 'af'],
  'medications': ['levothyroxine', 'warfarin', 'amiodarone', 'digoxin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'levothyroxine',
                    'drug_b': 'warfarin',
                    'severity': 'moderate',
                    'evidence': 'Thyroid hormone increases anticoagulant sensitivity'},
                   {'interaction_id': 'i2',
                    'drug_a': 'amiodarone',
                    'drug_b': 'warfarin',
                    'severity': 'major',
                    'evidence': 'CYP inhibition increases INR'},
                   {'interaction_id': 'i3',
                    'drug_a': 'amiodarone',
                    'drug_b': 'digoxin',
                    'severity': 'major',
                    'evidence': 'P-gp inhibition raises digoxin levels'},
                   {'interaction_id': 'i4',
                    'drug_a': 'digoxin',
                    'drug_b': 'levothyroxine',
                    'severity': 'moderate',
                    'evidence': 'Thyroid status alters digoxin sensitivity'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_22',
  'template_family': 'validation::liver-infection-002',
  'split': 'validation',
  'age': 73,
  'labs': {'egfr': 66, 'creatinine': 1.1, 'potassium': 4.1, 'inr': 1.2, 'alt': 98, 'ast': 90},
  'diagnoses': ['hepatitis', 'hypertension'],
  'medications': ['isoniazid', 'rifampin', 'acetaminophen', 'warfarin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'isoniazid',
                    'drug_b': 'rifampin',
                    'severity': 'major',
                    'evidence': 'Additive hepatotoxicity'},
                   {'interaction_id': 'i2',
                    'drug_a': 'acetaminophen',
                    'drug_b': 'isoniazid',
                    'severity': 'major',
                    'evidence': 'Increased toxic metabolite formation'},
                   {'interaction_id': 'i3',
                    'drug_a': 'rifampin',
                    'drug_b': 'warfarin',
                    'severity': 'major',
                    'evidence': 'Enzyme induction reduces anticoagulation'},
                   {'interaction_id': 'i4',
                    'drug_a': 'acetaminophen',
                    'drug_b': 'warfarin',
                    'severity': 'moderate',
                    'evidence': 'INR variability'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_23',
  'template_family': 'train::gout-polypharmacy-002',
  'split': 'train',
  'age': 77,
  'labs': {'egfr': 49, 'creatinine': 1.5, 'potassium': 4.6, 'inr': 1},
  'diagnoses': ['gout', 'hypertension'],
  'medications': ['colchicine', 'verapamil', 'atorvastatin', 'clarithromycin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'colchicine',
                    'drug_b': 'clarithromycin',
                    'severity': 'contraindicated',
                    'evidence': 'Severe colchicine toxicity risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'colchicine',
                    'drug_b': 'verapamil',
                    'severity': 'major',
                    'evidence': 'P-gp inhibition increases levels'},
                   {'interaction_id': 'i3',
                    'drug_a': 'atorvastatin',
                    'drug_b': 'clarithromycin',
                    'severity': 'major',
                    'evidence': 'Myopathy risk'},
                   {'interaction_id': 'i4',
                    'drug_a': 'atorvastatin',
                    'drug_b': 'verapamil',
                    'severity': 'moderate',
                    'evidence': 'CYP3A4 interaction'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_24',
  'template_family': 'validation::bleed-risk-002',
  'split': 'validation',
  'age': 85,
  'labs': {'egfr': 52, 'creatinine': 1.3, 'potassium': 4.4, 'inr': 3.3},
  'diagnoses': ['af', 'hypertension'],
  'medications': ['warfarin', 'aspirin', 'ibuprofen', 'prednisone'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'warfarin',
                    'drug_b': 'aspirin',
                    'severity': 'major',
                    'evidence': 'Dual antithrombotic increases bleeding'},
                   {'interaction_id': 'i2',
                    'drug_a': 'warfarin',
                    'drug_b': 'ibuprofen',
                    'severity': 'major',
                    'evidence': 'NSAID increases GI bleeding risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'aspirin',
                    'drug_b': 'ibuprofen',
                    'severity': 'moderate',
                    'evidence': 'Reduced antiplatelet effect'},
                   {'interaction_id': 'i4',
                    'drug_a': 'prednisone',
                    'drug_b': 'ibuprofen',
                    'severity': 'major',
                    'evidence': 'Ulcer risk increased'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_25',
  'template_family': 'train::transplant-infection-002',
  'split': 'train',
  'age': 70,
  'labs': {'egfr': 54, 'creatinine': 1.4, 'potassium': 4.5, 'inr': 1},
  'diagnoses': ['transplant', 'hypertension'],
  'medications': ['tacrolimus', 'fluconazole', 'azithromycin', 'prednisone'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'tacrolimus',
                    'drug_b': 'fluconazole',
                    'severity': 'major',
                    'evidence': 'CYP inhibition increases tacrolimus toxicity'},
                   {'interaction_id': 'i2',
                    'drug_a': 'tacrolimus',
                    'drug_b': 'azithromycin',
                    'severity': 'moderate',
                    'evidence': 'QT prolongation risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'fluconazole',
                    'drug_b': 'azithromycin',
                    'severity': 'moderate',
                    'evidence': 'QT prolongation'},
                   {'interaction_id': 'i4',
                    'drug_a': 'prednisone',
                    'drug_b': 'tacrolimus',
                    'severity': 'moderate',
                    'evidence': 'Additive immunosuppression'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_26',
  'template_family': 'validation::seizure-anticoag-002',
  'split': 'validation',
  'age': 68,
  'labs': {'egfr': 69, 'creatinine': 1, 'potassium': 4.2, 'inr': 2.4},
  'diagnoses': ['epilepsy', 'af'],
  'medications': ['phenytoin', 'warfarin', 'amiodarone', 'omeprazole'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'phenytoin',
                    'drug_b': 'warfarin',
                    'severity': 'major',
                    'evidence': 'Enzyme induction alters INR unpredictably'},
                   {'interaction_id': 'i2',
                    'drug_a': 'amiodarone',
                    'drug_b': 'warfarin',
                    'severity': 'major',
                    'evidence': 'Increases INR via inhibition'},
                   {'interaction_id': 'i3',
                    'drug_a': 'phenytoin',
                    'drug_b': 'amiodarone',
                    'severity': 'moderate',
                    'evidence': 'Metabolic competition'},
                   {'interaction_id': 'i4',
                    'drug_a': 'omeprazole',
                    'drug_b': 'phenytoin',
                    'severity': 'moderate',
                    'evidence': 'Increases phenytoin levels'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_27',
  'template_family': 'train::elderly-cns-002',
  'split': 'train',
  'age': 89,
  'labs': {'egfr': 48, 'creatinine': 1.5, 'potassium': 4.6, 'inr': 1},
  'diagnoses': ['insomnia', 'anxiety'],
  'medications': ['zolpidem', 'lorazepam', 'quetiapine', 'tramadol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'zolpidem',
                    'drug_b': 'lorazepam',
                    'severity': 'major',
                    'evidence': 'Additive CNS depression'},
                   {'interaction_id': 'i2',
                    'drug_a': 'lorazepam',
                    'drug_b': 'quetiapine',
                    'severity': 'major',
                    'evidence': 'Sedation and fall risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'tramadol',
                    'drug_b': 'quetiapine',
                    'severity': 'moderate',
                    'evidence': 'Seizure threshold lowered'},
                   {'interaction_id': 'i4',
                    'drug_a': 'zolpidem',
                    'drug_b': 'tramadol',
                    'severity': 'moderate',
                    'evidence': 'Respiratory depression risk'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_28',
  'template_family': 'validation::cardio-polypharmacy-002',
  'split': 'validation',
  'age': 76,
  'labs': {'egfr': 60, 'creatinine': 1.2, 'potassium': 4.3, 'inr': 1},
  'diagnoses': ['hypertension', 'angina'],
  'medications': ['metoprolol', 'verapamil', 'digoxin', 'aspirin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'metoprolol',
                    'drug_b': 'verapamil',
                    'severity': 'major',
                    'evidence': 'Bradycardia and AV block risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'verapamil',
                    'drug_b': 'digoxin',
                    'severity': 'major',
                    'evidence': 'Increases digoxin levels'},
                   {'interaction_id': 'i3',
                    'drug_a': 'metoprolol',
                    'drug_b': 'digoxin',
                    'severity': 'moderate',
                    'evidence': 'Additive heart rate reduction'},
                   {'interaction_id': 'i4',
                    'drug_a': 'aspirin',
                    'drug_b': 'metoprolol',
                    'severity': 'minor',
                    'evidence': 'Minimal interaction'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_29',
  'template_family': 'train::renal-antibiotic-002',
  'split': 'train',
  'age': 80,
  'labs': {'egfr': 44, 'creatinine': 1.8, 'potassium': 5.1, 'inr': 1},
  'diagnoses': ['ckd', 'infection'],
  'medications': ['vancomycin', 'piperacillin-tazobactam', 'lisinopril', 'furosemide'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'vancomycin',
                    'drug_b': 'piperacillin-tazobactam',
                    'severity': 'major',
                    'evidence': 'Increased nephrotoxicity risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'lisinopril',
                    'drug_b': 'vancomycin',
                    'severity': 'moderate',
                    'evidence': 'Renal function decline risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'furosemide',
                    'drug_b': 'vancomycin',
                    'severity': 'moderate',
                    'evidence': 'Ototoxicity risk increased'},
                   {'interaction_id': 'i4',
                    'drug_a': 'lisinopril',
                    'drug_b': 'furosemide',
                    'severity': 'moderate',
                    'evidence': 'Hypotension risk'}],
  'required_regimens': [],
  'substitution_options': []},
 {'case_id': 'M_30',
  'template_family': 'validation::endocrine-mix-002',
  'split': 'validation',
  'age': 71,
  'labs': {'egfr': 63, 'creatinine': 1.1, 'potassium': 4.2, 'inr': 1},
  'diagnoses': ['diabetes', 'hypothyroidism'],
  'medications': ['metformin', 'levothyroxine', 'propranolol', 'insulin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'propranolol',
                    'drug_b': 'insulin',
                    'severity': 'major',
                    'evidence': 'Masks hypoglycemia symptoms'},
                   {'interaction_id': 'i2',
                    'drug_a': 'levothyroxine',
                    'drug_b': 'insulin',
                    'severity': 'moderate',
                    'evidence': 'Thyroid hormone alters glucose control'},
                   {'interaction_id': 'i3',
                    'drug_a': 'propranolol',
                    'drug_b': 'metformin',
                    'severity': 'moderate',
                    'evidence': 'May blunt hypoglycemia awareness'},
                   {'interaction_id': 'i4',
                    'drug_a': 'levothyroxine',
                    'drug_b': 'propranolol',
                    'severity': 'moderate',
                    'evidence': 'Opposing cardiac effects'}],
  'required_regimens': [],
  'substitution_options': []}]

VALIDATED_HARD_CASES: List[Case] = [{'case_id': 'H_11',
  'template_family': 'train::af-ckd-hf-tradeoff-001',
  'split': 'train',
  'age': 86,
  'labs': {'egfr': 38, 'creatinine': 2, 'potassium': 5.3, 'inr': 2.8},
  'diagnoses': ['atrial fibrillation', 'heart failure', 'ckd'],
  'medications': ['warfarin', 'amiodarone', 'spironolactone', 'lisinopril', 'furosemide'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'warfarin',
                    'drug_b': 'amiodarone',
                    'severity': 'major',
                    'evidence': 'CYP2C9 inhibition increases INR'},
                   {'interaction_id': 'i2',
                    'drug_a': 'lisinopril',
                    'drug_b': 'spironolactone',
                    'severity': 'major',
                    'evidence': 'Severe hyperkalemia risk in CKD'},
                   {'interaction_id': 'i3',
                    'drug_a': 'amiodarone',
                    'drug_b': 'spironolactone',
                    'severity': 'moderate',
                    'evidence': 'QT prolongation risk'},
                   {'interaction_id': 'i4',
                    'drug_a': 'furosemide',
                    'drug_b': 'lisinopril',
                    'severity': 'moderate',
                    'evidence': 'Hypotension and renal perfusion risk'}],
  'required_regimens': ['H_11-R1', 'H_11-R2'],
  'substitution_options': [{'regimen_id': 'H_11-R1',
                            'replace_drug': 'warfarin',
                            'with_drug': 'apixaban',
                            'target_condition': 'atrial fibrillation',
                            'expected_risk_delta': 0.3,
                            'rationale': 'Avoid CYP interaction'},
                           {'regimen_id': 'H_11-R2',
                            'replace_drug': 'amiodarone',
                            'with_drug': 'bisoprolol',
                            'target_condition': 'rate control',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Reduce QT and INR interaction'},
                           {'regimen_id': 'H_11-R3',
                            'replace_drug': 'spironolactone',
                            'with_drug': 'eplerenone',
                            'target_condition': 'heart failure',
                            'expected_risk_delta': 0.1,
                            'rationale': 'Lower hyperkalemia risk'}]},
 {'case_id': 'H_12',
  'template_family': 'validation::hepatic-anticoag-tradeoff-001',
  'split': 'validation',
  'age': 78,
  'labs': {'egfr': 55, 'creatinine': 1.3, 'potassium': 4.5, 'inr': 3.4, 'alt': 120, 'ast': 110},
  'diagnoses': ['atrial fibrillation', 'hepatic impairment'],
  'medications': ['warfarin', 'fluconazole', 'atorvastatin', 'aspirin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'warfarin',
                    'drug_b': 'fluconazole',
                    'severity': 'major',
                    'evidence': 'Strong CYP inhibition increases INR'},
                   {'interaction_id': 'i2',
                    'drug_a': 'atorvastatin',
                    'drug_b': 'fluconazole',
                    'severity': 'major',
                    'evidence': 'Increased statin toxicity'},
                   {'interaction_id': 'i3',
                    'drug_a': 'warfarin',
                    'drug_b': 'aspirin',
                    'severity': 'major',
                    'evidence': 'Additive bleeding risk'},
                   {'interaction_id': 'i4',
                    'drug_a': 'aspirin',
                    'drug_b': 'atorvastatin',
                    'severity': 'minor',
                    'evidence': 'Minimal interaction'}],
  'required_regimens': ['H_12-R1', 'H_12-R2'],
  'substitution_options': [{'regimen_id': 'H_12-R1',
                            'replace_drug': 'warfarin',
                            'with_drug': 'dabigatran',
                            'target_condition': 'atrial fibrillation',
                            'expected_risk_delta': 0.25,
                            'rationale': 'Avoid CYP pathway'},
                           {'regimen_id': 'H_12-R2',
                            'replace_drug': 'fluconazole',
                            'with_drug': 'micafungin',
                            'target_condition': 'fungal infection',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Less CYP inhibition'},
                           {'regimen_id': 'H_12-R3',
                            'replace_drug': 'atorvastatin',
                            'with_drug': 'pravastatin',
                            'target_condition': 'lipids',
                            'expected_risk_delta': 0.15,
                            'rationale': 'Reduced hepatic metabolism'}]},
 {'case_id': 'H_13',
  'template_family': 'train::qt-polypharmacy-tradeoff-001',
  'split': 'train',
  'age': 88,
  'labs': {'egfr': 50, 'creatinine': 1.4, 'potassium': 3.4, 'inr': 1},
  'diagnoses': ['arrhythmia', 'infection', 'depression'],
  'medications': ['amiodarone', 'levofloxacin', 'citalopram', 'ondansetron'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'amiodarone',
                    'drug_b': 'levofloxacin',
                    'severity': 'major',
                    'evidence': 'QT prolongation torsades risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'citalopram',
                    'drug_b': 'ondansetron',
                    'severity': 'major',
                    'evidence': 'Additive QT prolongation'},
                   {'interaction_id': 'i3',
                    'drug_a': 'amiodarone',
                    'drug_b': 'citalopram',
                    'severity': 'major',
                    'evidence': 'High arrhythmia risk'},
                   {'interaction_id': 'i4',
                    'drug_a': 'levofloxacin',
                    'drug_b': 'ondansetron',
                    'severity': 'moderate',
                    'evidence': 'QT additive effect'}],
  'required_regimens': ['H_13-R1', 'H_13-R2'],
  'substitution_options': [{'regimen_id': 'H_13-R1',
                            'replace_drug': 'levofloxacin',
                            'with_drug': 'amoxicillin',
                            'target_condition': 'infection',
                            'expected_risk_delta': 0.3,
                            'rationale': 'No QT prolongation'},
                           {'regimen_id': 'H_13-R2',
                            'replace_drug': 'ondansetron',
                            'with_drug': 'metoclopramide',
                            'target_condition': 'nausea',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Lower QT risk'},
                           {'regimen_id': 'H_13-R3',
                            'replace_drug': 'citalopram',
                            'with_drug': 'sertraline',
                            'target_condition': 'depression',
                            'expected_risk_delta': 0.15,
                            'rationale': 'Lower QT liability'}]},
 {'case_id': 'H_14',
  'template_family': 'train::ckd-infection-nephro-001',
  'split': 'train',
  'age': 82,
  'labs': {'egfr': 32, 'creatinine': 2.3, 'potassium': 5.2, 'inr': 1.1},
  'diagnoses': ['ckd', 'sepsis'],
  'medications': ['vancomycin', 'piperacillin-tazobactam', 'lisinopril', 'furosemide'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'vancomycin',
                    'drug_b': 'piperacillin-tazobactam',
                    'severity': 'major',
                    'evidence': 'Synergistic nephrotoxicity'},
                   {'interaction_id': 'i2',
                    'drug_a': 'lisinopril',
                    'drug_b': 'vancomycin',
                    'severity': 'moderate',
                    'evidence': 'Renal injury risk worsened'},
                   {'interaction_id': 'i3',
                    'drug_a': 'furosemide',
                    'drug_b': 'vancomycin',
                    'severity': 'moderate',
                    'evidence': 'Ototoxicity risk increased'},
                   {'interaction_id': 'i4',
                    'drug_a': 'lisinopril',
                    'drug_b': 'piperacillin-tazobactam',
                    'severity': 'moderate',
                    'evidence': 'Renal perfusion compromise'}],
  'required_regimens': ['H_14-R1', 'H_14-R2'],
  'substitution_options': [{'regimen_id': 'H_14-R1',
                            'replace_drug': 'vancomycin',
                            'with_drug': 'linezolid',
                            'target_condition': 'mrsa',
                            'expected_risk_delta': 0.3,
                            'rationale': 'Avoid nephrotoxicity'},
                           {'regimen_id': 'H_14-R2',
                            'replace_drug': 'piperacillin-tazobactam',
                            'with_drug': 'cefepime',
                            'target_condition': 'gram negative',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Lower renal injury risk'},
                           {'regimen_id': 'H_14-R3',
                            'replace_drug': 'lisinopril',
                            'with_drug': 'amlodipine',
                            'target_condition': 'hypertension',
                            'expected_risk_delta': 0.1,
                            'rationale': 'Avoid renal perfusion impact'}]},
 {'case_id': 'H_15',
  'template_family': 'validation::diabetes-cardiac-tradeoff-001',
  'split': 'validation',
  'age': 80,
  'labs': {'egfr': 41, 'creatinine': 1.9, 'potassium': 4.9, 'inr': 1},
  'diagnoses': ['diabetes', 'heart failure'],
  'medications': ['metformin', 'empagliflozin', 'furosemide', 'lisinopril', 'insulin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'empagliflozin',
                    'drug_b': 'furosemide',
                    'severity': 'major',
                    'evidence': 'Volume depletion risk; elevated clinical risk requiring '
                                'escalation'},
                   {'interaction_id': 'i2',
                    'drug_a': 'metformin',
                    'drug_b': 'empagliflozin',
                    'severity': 'moderate',
                    'evidence': 'Lactic acidosis risk in CKD'},
                   {'interaction_id': 'i3',
                    'drug_a': 'lisinopril',
                    'drug_b': 'furosemide',
                    'severity': 'moderate',
                    'evidence': 'Hypotension risk'},
                   {'interaction_id': 'i4',
                    'drug_a': 'insulin',
                    'drug_b': 'empagliflozin',
                    'severity': 'moderate',
                    'evidence': 'Hypoglycemia risk increased'}],
  'required_regimens': ['H_15-R1', 'H_15-R2'],
  'substitution_options': [{'regimen_id': 'H_15-R1',
                            'replace_drug': 'metformin',
                            'with_drug': 'linagliptin',
                            'target_condition': 'diabetes',
                            'expected_risk_delta': 0.25,
                            'rationale': 'Safe in CKD'},
                           {'regimen_id': 'H_15-R2',
                            'replace_drug': 'empagliflozin',
                            'with_drug': 'glipizide',
                            'target_condition': 'diabetes',
                            'expected_risk_delta': 0.1,
                            'rationale': 'Avoid dehydration risk'},
                           {'regimen_id': 'H_15-R3',
                            'replace_drug': 'lisinopril',
                            'with_drug': 'hydralazine',
                            'target_condition': 'heart failure',
                            'expected_risk_delta': 0.1,
                            'rationale': 'Reduce renal risk'}]},
 {'case_id': 'H_16',
  'template_family': 'train::bleeding-polypharmacy-003',
  'split': 'train',
  'age': 87,
  'labs': {'egfr': 53, 'creatinine': 1.3, 'potassium': 4.5, 'inr': 3.5},
  'diagnoses': ['af', 'arthritis'],
  'medications': ['warfarin', 'aspirin', 'clopidogrel', 'ibuprofen'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'warfarin',
                    'drug_b': 'aspirin',
                    'severity': 'major',
                    'evidence': 'Bleeding risk increased'},
                   {'interaction_id': 'i2',
                    'drug_a': 'warfarin',
                    'drug_b': 'clopidogrel',
                    'severity': 'major',
                    'evidence': 'Triple therapy hemorrhage risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'aspirin',
                    'drug_b': 'ibuprofen',
                    'severity': 'moderate',
                    'evidence': 'Reduced cardioprotection'},
                   {'interaction_id': 'i4',
                    'drug_a': 'ibuprofen',
                    'drug_b': 'warfarin',
                    'severity': 'major',
                    'evidence': 'GI bleeding risk'}],
  'required_regimens': ['H_16-R1', 'H_16-R2'],
  'substitution_options': [{'regimen_id': 'H_16-R1',
                            'replace_drug': 'ibuprofen',
                            'with_drug': 'acetaminophen',
                            'target_condition': 'pain',
                            'expected_risk_delta': 0.3,
                            'rationale': 'Lower bleeding risk'},
                           {'regimen_id': 'H_16-R2',
                            'replace_drug': 'aspirin',
                            'with_drug': 'none',
                            'target_condition': 'antiplatelet',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Reduce triple therapy risk'},
                           {'regimen_id': 'H_16-R3',
                            'replace_drug': 'warfarin',
                            'with_drug': 'apixaban',
                            'target_condition': 'af',
                            'expected_risk_delta': 0.15,
                            'rationale': 'Lower bleeding risk profile'}]},
 {'case_id': 'H_17',
  'template_family': 'train::transplant-cyp-tradeoff-002',
  'split': 'train',
  'age': 72,
  'labs': {'egfr': 48, 'creatinine': 1.6, 'potassium': 4.6, 'inr': 1},
  'diagnoses': ['renal transplant', 'hypertension'],
  'medications': ['tacrolimus', 'clarithromycin', 'fluconazole', 'prednisone'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'tacrolimus',
                    'drug_b': 'clarithromycin',
                    'severity': 'major',
                    'evidence': 'Strong CYP3A4 inhibition increases tacrolimus toxicity'},
                   {'interaction_id': 'i2',
                    'drug_a': 'tacrolimus',
                    'drug_b': 'fluconazole',
                    'severity': 'major',
                    'evidence': 'Further CYP inhibition increases levels'},
                   {'interaction_id': 'i3',
                    'drug_a': 'clarithromycin',
                    'drug_b': 'fluconazole',
                    'severity': 'moderate',
                    'evidence': 'Additive QT prolongation'},
                   {'interaction_id': 'i4',
                    'drug_a': 'prednisone',
                    'drug_b': 'tacrolimus',
                    'severity': 'moderate',
                    'evidence': 'Additive immunosuppression'}],
  'required_regimens': ['H_17-R1', 'H_17-R2'],
  'substitution_options': [{'regimen_id': 'H_17-R1',
                            'replace_drug': 'clarithromycin',
                            'with_drug': 'azithromycin',
                            'target_condition': 'infection',
                            'expected_risk_delta': 0.3,
                            'rationale': 'Less CYP inhibition'},
                           {'regimen_id': 'H_17-R2',
                            'replace_drug': 'fluconazole',
                            'with_drug': 'echinocandin',
                            'target_condition': 'fungal infection',
                            'expected_risk_delta': 0.25,
                            'rationale': 'Avoid CYP interaction'},
                           {'regimen_id': 'H_17-R3',
                            'replace_drug': 'tacrolimus',
                            'with_drug': 'cyclosporine',
                            'target_condition': 'immunosuppression',
                            'expected_risk_delta': 0.1,
                            'rationale': 'Different metabolic pathway'}]},
 {'case_id': 'H_18',
  'template_family': 'validation::serotonin-syndrome-tradeoff-002',
  'split': 'validation',
  'age': 75,
  'labs': {'egfr': 60, 'creatinine': 1.1, 'potassium': 4.2, 'inr': 1},
  'diagnoses': ['depression', 'infection', 'pain'],
  'medications': ['sertraline', 'linezolid', 'tramadol', 'ondansetron'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'sertraline',
                    'drug_b': 'linezolid',
                    'severity': 'major',
                    'evidence': 'Serotonin syndrome risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'tramadol',
                    'drug_b': 'sertraline',
                    'severity': 'major',
                    'evidence': 'Additive serotonergic toxicity'},
                   {'interaction_id': 'i3',
                    'drug_a': 'linezolid',
                    'drug_b': 'tramadol',
                    'severity': 'major',
                    'evidence': 'Severe serotonin syndrome'},
                   {'interaction_id': 'i4',
                    'drug_a': 'ondansetron',
                    'drug_b': 'sertraline',
                    'severity': 'moderate',
                    'evidence': 'QT prolongation'}],
  'required_regimens': ['H_18-R1', 'H_18-R2'],
  'substitution_options': [{'regimen_id': 'H_18-R1',
                            'replace_drug': 'linezolid',
                            'with_drug': 'doxycycline',
                            'target_condition': 'infection',
                            'expected_risk_delta': 0.3,
                            'rationale': 'No MAOI effect'},
                           {'regimen_id': 'H_18-R2',
                            'replace_drug': 'tramadol',
                            'with_drug': 'acetaminophen',
                            'target_condition': 'pain',
                            'expected_risk_delta': 0.25,
                            'rationale': 'No serotonergic effect'},
                           {'regimen_id': 'H_18-R3',
                            'replace_drug': 'sertraline',
                            'with_drug': 'mirtazapine',
                            'target_condition': 'depression',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Lower serotonin syndrome risk'}]},
 {'case_id': 'H_19',
  'template_family': 'train::gout-cyp-toxicity-003',
  'split': 'train',
  'age': 79,
  'labs': {'egfr': 42, 'creatinine': 1.8, 'potassium': 4.7, 'inr': 1},
  'diagnoses': ['gout', 'ckd'],
  'medications': ['colchicine', 'clarithromycin', 'verapamil', 'atorvastatin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'colchicine',
                    'drug_b': 'clarithromycin',
                    'severity': 'contraindicated',
                    'evidence': 'Fatal colchicine toxicity risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'colchicine',
                    'drug_b': 'verapamil',
                    'severity': 'major',
                    'evidence': 'P-gp inhibition increases levels'},
                   {'interaction_id': 'i3',
                    'drug_a': 'atorvastatin',
                    'drug_b': 'clarithromycin',
                    'severity': 'major',
                    'evidence': 'Myopathy risk'},
                   {'interaction_id': 'i4',
                    'drug_a': 'atorvastatin',
                    'drug_b': 'verapamil',
                    'severity': 'moderate',
                    'evidence': 'CYP3A4 interaction'}],
  'required_regimens': ['H_19-R1', 'H_19-R2'],
  'substitution_options': [{'regimen_id': 'H_19-R1',
                            'replace_drug': 'clarithromycin',
                            'with_drug': 'azithromycin',
                            'target_condition': 'infection',
                            'expected_risk_delta': 0.3,
                            'rationale': 'Less CYP inhibition'},
                           {'regimen_id': 'H_19-R2',
                            'replace_drug': 'colchicine',
                            'with_drug': 'prednisone',
                            'target_condition': 'gout',
                            'expected_risk_delta': 0.25,
                            'rationale': 'Avoid toxicity'},
                           {'regimen_id': 'H_19-R3',
                            'replace_drug': 'atorvastatin',
                            'with_drug': 'rosuvastatin',
                            'target_condition': 'lipids',
                            'expected_risk_delta': 0.15,
                            'rationale': 'Less CYP metabolism'}]},
 {'case_id': 'H_20',
  'template_family': 'validation::respiratory-cns-tradeoff-002',
  'split': 'validation',
  'age': 90,
  'labs': {'egfr': 45, 'creatinine': 1.7, 'potassium': 4.5, 'inr': 1},
  'diagnoses': ['insomnia', 'pain', 'anxiety'],
  'medications': ['zolpidem', 'lorazepam', 'tramadol', 'gabapentin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'zolpidem',
                    'drug_b': 'lorazepam',
                    'severity': 'major',
                    'evidence': 'CNS depression'},
                   {'interaction_id': 'i2',
                    'drug_a': 'tramadol',
                    'drug_b': 'gabapentin',
                    'severity': 'major',
                    'evidence': 'Respiratory depression risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'lorazepam',
                    'drug_b': 'gabapentin',
                    'severity': 'major',
                    'evidence': 'Sedation and falls'},
                   {'interaction_id': 'i4',
                    'drug_a': 'zolpidem',
                    'drug_b': 'tramadol',
                    'severity': 'moderate',
                    'evidence': 'Additive CNS depression'}],
  'required_regimens': ['H_20-R1', 'H_20-R2'],
  'substitution_options': [{'regimen_id': 'H_20-R1',
                            'replace_drug': 'zolpidem',
                            'with_drug': 'melatonin',
                            'target_condition': 'insomnia',
                            'expected_risk_delta': 0.3,
                            'rationale': 'Safer in elderly'},
                           {'regimen_id': 'H_20-R2',
                            'replace_drug': 'lorazepam',
                            'with_drug': 'buspirone',
                            'target_condition': 'anxiety',
                            'expected_risk_delta': 0.25,
                            'rationale': 'Less sedation'},
                           {'regimen_id': 'H_20-R3',
                            'replace_drug': 'tramadol',
                            'with_drug': 'acetaminophen',
                            'target_condition': 'pain',
                            'expected_risk_delta': 0.2,
                            'rationale': 'No respiratory depression'}]},
 {'case_id': 'H_21',
  'template_family': 'train::cardiac-conduction-tradeoff-002',
  'split': 'train',
  'age': 81,
  'labs': {'egfr': 58, 'creatinine': 1.3, 'potassium': 4.4, 'inr': 1},
  'diagnoses': ['af', 'hypertension'],
  'medications': ['metoprolol', 'verapamil', 'digoxin', 'amiodarone'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'metoprolol',
                    'drug_b': 'verapamil',
                    'severity': 'major',
                    'evidence': 'AV block risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'verapamil',
                    'drug_b': 'digoxin',
                    'severity': 'major',
                    'evidence': 'Increases digoxin levels'},
                   {'interaction_id': 'i3',
                    'drug_a': 'amiodarone',
                    'drug_b': 'digoxin',
                    'severity': 'major',
                    'evidence': 'P-gp inhibition'},
                   {'interaction_id': 'i4',
                    'drug_a': 'amiodarone',
                    'drug_b': 'verapamil',
                    'severity': 'major',
                    'evidence': 'Severe bradycardia'}],
  'required_regimens': ['H_21-R1', 'H_21-R2'],
  'substitution_options': [{'regimen_id': 'H_21-R1',
                            'replace_drug': 'verapamil',
                            'with_drug': 'amlodipine',
                            'target_condition': 'hypertension',
                            'expected_risk_delta': 0.3,
                            'rationale': 'No AV node suppression'},
                           {'regimen_id': 'H_21-R2',
                            'replace_drug': 'digoxin',
                            'with_drug': 'none',
                            'target_condition': 'rate control',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Reduce toxicity risk'},
                           {'regimen_id': 'H_21-R3',
                            'replace_drug': 'amiodarone',
                            'with_drug': 'bisoprolol',
                            'target_condition': 'af',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Simplify regimen'}]},
 {'case_id': 'H_22',
  'template_family': 'validation::hepatic-mixed-toxicity-002',
  'split': 'validation',
  'age': 76,
  'labs': {'egfr': 62, 'creatinine': 1.2, 'potassium': 4.3, 'inr': 1.3, 'alt': 130, 'ast': 115},
  'diagnoses': ['hepatitis', 'infection'],
  'medications': ['isoniazid', 'rifampin', 'acetaminophen', 'phenytoin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'isoniazid',
                    'drug_b': 'rifampin',
                    'severity': 'major',
                    'evidence': 'Hepatotoxicity'},
                   {'interaction_id': 'i2',
                    'drug_a': 'acetaminophen',
                    'drug_b': 'isoniazid',
                    'severity': 'major',
                    'evidence': 'Toxic metabolite accumulation'},
                   {'interaction_id': 'i3',
                    'drug_a': 'rifampin',
                    'drug_b': 'phenytoin',
                    'severity': 'moderate',
                    'evidence': 'Enzyme induction alters levels'},
                   {'interaction_id': 'i4',
                    'drug_a': 'phenytoin',
                    'drug_b': 'isoniazid',
                    'severity': 'major',
                    'evidence': 'Metabolism inhibition toxicity'}],
  'required_regimens': ['H_22-R1', 'H_22-R2'],
  'substitution_options': [{'regimen_id': 'H_22-R1',
                            'replace_drug': 'acetaminophen',
                            'with_drug': 'ibuprofen',
                            'target_condition': 'pain',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Reduce liver burden'},
                           {'regimen_id': 'H_22-R2',
                            'replace_drug': 'isoniazid',
                            'with_drug': 'levofloxacin',
                            'target_condition': 'tb',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Less hepatotoxic'},
                           {'regimen_id': 'H_22-R3',
                            'replace_drug': 'phenytoin',
                            'with_drug': 'levetiracetam',
                            'target_condition': 'seizure',
                            'expected_risk_delta': 0.25,
                            'rationale': 'Minimal hepatic metabolism'}]},
 {'case_id': 'H_23',
  'template_family': 'train::endocrine-cardiac-003',
  'split': 'train',
  'age': 74,
  'labs': {'egfr': 60, 'creatinine': 1.1, 'potassium': 4.2, 'inr': 1},
  'diagnoses': ['diabetes', 'af'],
  'medications': ['insulin', 'propranolol', 'warfarin', 'amiodarone'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'propranolol',
                    'drug_b': 'insulin',
                    'severity': 'major',
                    'evidence': 'Masks hypoglycemia'},
                   {'interaction_id': 'i2',
                    'drug_a': 'warfarin',
                    'drug_b': 'amiodarone',
                    'severity': 'major',
                    'evidence': 'INR increase'},
                   {'interaction_id': 'i3',
                    'drug_a': 'propranolol',
                    'drug_b': 'amiodarone',
                    'severity': 'major',
                    'evidence': 'Bradycardia risk'},
                   {'interaction_id': 'i4',
                    'drug_a': 'warfarin',
                    'drug_b': 'insulin',
                    'severity': 'minor',
                    'evidence': 'Minimal interaction'}],
  'required_regimens': ['H_23-R1', 'H_23-R2'],
  'substitution_options': [{'regimen_id': 'H_23-R1',
                            'replace_drug': 'propranolol',
                            'with_drug': 'metoprolol',
                            'target_condition': 'af',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Less hypoglycemia masking'},
                           {'regimen_id': 'H_23-R2',
                            'replace_drug': 'amiodarone',
                            'with_drug': 'diltiazem',
                            'target_condition': 'rate control',
                            'expected_risk_delta': 0.15,
                            'rationale': 'Reduce toxicity'},
                           {'regimen_id': 'H_23-R3',
                            'replace_drug': 'warfarin',
                            'with_drug': 'apixaban',
                            'target_condition': 'af',
                            'expected_risk_delta': 0.2,
                            'rationale': 'More stable anticoagulation'}]},
 {'case_id': 'H_24',
  'template_family': 'validation::renal-hyperkalemia-003',
  'split': 'validation',
  'age': 85,
  'labs': {'egfr': 35, 'creatinine': 2.2, 'potassium': 5.6, 'inr': 1},
  'diagnoses': ['ckd', 'hypertension'],
  'medications': ['lisinopril', 'spironolactone', 'trimethoprim', 'losartan'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'lisinopril',
                    'drug_b': 'losartan',
                    'severity': 'major',
                    'evidence': 'Dual RAAS blockade'},
                   {'interaction_id': 'i2',
                    'drug_a': 'spironolactone',
                    'drug_b': 'trimethoprim',
                    'severity': 'major',
                    'evidence': 'Severe hyperkalemia'},
                   {'interaction_id': 'i3',
                    'drug_a': 'lisinopril',
                    'drug_b': 'spironolactone',
                    'severity': 'major',
                    'evidence': 'Potassium elevation'},
                   {'interaction_id': 'i4',
                    'drug_a': 'losartan',
                    'drug_b': 'trimethoprim',
                    'severity': 'moderate',
                    'evidence': 'Additive potassium retention'}],
  'required_regimens': ['H_24-R1', 'H_24-R2'],
  'substitution_options': [{'regimen_id': 'H_24-R1',
                            'replace_drug': 'spironolactone',
                            'with_drug': 'furosemide',
                            'target_condition': 'bp',
                            'expected_risk_delta': 0.3,
                            'rationale': 'Reduce potassium'},
                           {'regimen_id': 'H_24-R2',
                            'replace_drug': 'trimethoprim',
                            'with_drug': 'nitrofurantoin',
                            'target_condition': 'uti',
                            'expected_risk_delta': 0.25,
                            'rationale': 'Avoid potassium effect'},
                           {'regimen_id': 'H_24-R3',
                            'replace_drug': 'losartan',
                            'with_drug': 'amlodipine',
                            'target_condition': 'bp',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Avoid RAAS stacking'}]},
 {'case_id': 'H_25',
  'template_family': 'train::anticoag-cyp-bleed-004',
  'split': 'train',
  'age': 83,
  'labs': {'egfr': 52, 'creatinine': 1.4, 'potassium': 4.6, 'inr': 3.1},
  'diagnoses': ['atrial fibrillation', 'peptic ulcer disease'],
  'medications': ['warfarin', 'fluconazole', 'metronidazole', 'aspirin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'warfarin',
                    'drug_b': 'fluconazole',
                    'severity': 'major',
                    'evidence': 'CYP2C9 inhibition markedly increases INR'},
                   {'interaction_id': 'i2',
                    'drug_a': 'warfarin',
                    'drug_b': 'metronidazole',
                    'severity': 'major',
                    'evidence': 'Reduced metabolism increases bleeding risk'},
                   {'interaction_id': 'i3',
                    'drug_a': 'warfarin',
                    'drug_b': 'aspirin',
                    'severity': 'major',
                    'evidence': 'Additive antithrombotic effect increases GI bleeding'},
                   {'interaction_id': 'i4',
                    'drug_a': 'fluconazole',
                    'drug_b': 'metronidazole',
                    'severity': 'moderate',
                    'evidence': 'Additive QT prolongation risk in elderly'}],
  'required_regimens': ['H_25-R1', 'H_25-R2'],
  'substitution_options': [{'regimen_id': 'H_25-R1',
                            'replace_drug': 'warfarin',
                            'with_drug': 'apixaban',
                            'target_condition': 'atrial fibrillation',
                            'expected_risk_delta': 0.3,
                            'rationale': 'Avoid CYP-mediated INR variability'},
                           {'regimen_id': 'H_25-R2',
                            'replace_drug': 'metronidazole',
                            'with_drug': 'amoxicillin-clavulanate',
                            'target_condition': 'infection',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Less interaction with anticoagulants'},
                           {'regimen_id': 'H_25-R3',
                            'replace_drug': 'aspirin',
                            'with_drug': 'none',
                            'target_condition': 'antiplatelet',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Reduce bleeding burden'}]},
 {'case_id': 'H_26',
  'template_family': 'validation::electrolyte-arrhythmia-004',
  'split': 'validation',
  'age': 89,
  'labs': {'egfr': 40, 'creatinine': 1.9, 'potassium': 3.1, 'inr': 1},
  'diagnoses': ['heart failure', 'arrhythmia'],
  'medications': ['furosemide', 'digoxin', 'amiodarone', 'prednisone'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'furosemide',
                    'drug_b': 'digoxin',
                    'severity': 'major',
                    'evidence': 'Hypokalemia increases digoxin toxicity risk'},
                   {'interaction_id': 'i2',
                    'drug_a': 'amiodarone',
                    'drug_b': 'digoxin',
                    'severity': 'major',
                    'evidence': 'P-gp inhibition raises digoxin levels'},
                   {'interaction_id': 'i3',
                    'drug_a': 'prednisone',
                    'drug_b': 'furosemide',
                    'severity': 'moderate',
                    'evidence': 'Enhanced potassium loss'},
                   {'interaction_id': 'i4',
                    'drug_a': 'amiodarone',
                    'drug_b': 'furosemide',
                    'severity': 'moderate',
                    'evidence': 'Electrolyte imbalance increases arrhythmia risk'}],
  'required_regimens': ['H_26-R1', 'H_26-R2'],
  'substitution_options': [{'regimen_id': 'H_26-R1',
                            'replace_drug': 'furosemide',
                            'with_drug': 'torsemide',
                            'target_condition': 'heart failure',
                            'expected_risk_delta': 0.1,
                            'rationale': 'More stable pharmacokinetics'},
                           {'regimen_id': 'H_26-R2',
                            'replace_drug': 'digoxin',
                            'with_drug': 'bisoprolol',
                            'target_condition': 'rate control',
                            'expected_risk_delta': 0.3,
                            'rationale': 'Avoid narrow therapeutic index toxicity'},
                           {'regimen_id': 'H_26-R3',
                            'replace_drug': 'prednisone',
                            'with_drug': 'none',
                            'target_condition': 'inflammation',
                            'expected_risk_delta': 0.15,
                            'rationale': 'Reduce electrolyte disturbance'}]},
 {'case_id': 'H_27',
  'template_family': 'train::lipid-cyp-myopathy-004',
  'split': 'train',
  'age': 77,
  'labs': {'egfr': 58, 'creatinine': 1.2, 'potassium': 4.4, 'inr': 1},
  'diagnoses': ['dyslipidemia', 'infection'],
  'medications': ['simvastatin', 'clarithromycin', 'diltiazem', 'niacin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'simvastatin',
                    'drug_b': 'clarithromycin',
                    'severity': 'contraindicated',
                    'evidence': 'Severe rhabdomyolysis risk via CYP3A4 inhibition'},
                   {'interaction_id': 'i2',
                    'drug_a': 'simvastatin',
                    'drug_b': 'diltiazem',
                    'severity': 'major',
                    'evidence': 'Increased statin levels'},
                   {'interaction_id': 'i3',
                    'drug_a': 'simvastatin',
                    'drug_b': 'niacin',
                    'severity': 'major',
                    'evidence': 'Additive myopathy risk'},
                   {'interaction_id': 'i4',
                    'drug_a': 'clarithromycin',
                    'drug_b': 'diltiazem',
                    'severity': 'moderate',
                    'evidence': 'Bradycardia and hypotension risk'}],
  'required_regimens': ['H_27-R1', 'H_27-R2'],
  'substitution_options': [{'regimen_id': 'H_27-R1',
                            'replace_drug': 'simvastatin',
                            'with_drug': 'pravastatin',
                            'target_condition': 'lipids',
                            'expected_risk_delta': 0.3,
                            'rationale': 'Minimal CYP metabolism'},
                           {'regimen_id': 'H_27-R2',
                            'replace_drug': 'clarithromycin',
                            'with_drug': 'azithromycin',
                            'target_condition': 'infection',
                            'expected_risk_delta': 0.25,
                            'rationale': 'Lower CYP inhibition'},
                           {'regimen_id': 'H_27-R3',
                            'replace_drug': 'niacin',
                            'with_drug': 'ezetimibe',
                            'target_condition': 'lipids',
                            'expected_risk_delta': 0.15,
                            'rationale': 'Avoid myopathy risk'}]},
 {'case_id': 'H_28',
  'template_family': 'validation::anticholinergic-burden-002',
  'split': 'validation',
  'age': 91,
  'labs': {'egfr': 47, 'creatinine': 1.5, 'potassium': 4.3, 'inr': 1},
  'diagnoses': ['parkinsonism', 'urinary incontinence', 'depression'],
  'medications': ['benztropine', 'oxybutynin', 'amitriptyline', 'quetiapine'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'benztropine',
                    'drug_b': 'oxybutynin',
                    'severity': 'major',
                    'evidence': 'Severe anticholinergic burden causing delirium'},
                   {'interaction_id': 'i2',
                    'drug_a': 'amitriptyline',
                    'drug_b': 'oxybutynin',
                    'severity': 'major',
                    'evidence': 'Additive anticholinergic toxicity'},
                   {'interaction_id': 'i3',
                    'drug_a': 'quetiapine',
                    'drug_b': 'amitriptyline',
                    'severity': 'moderate',
                    'evidence': 'Sedation and QT prolongation'},
                   {'interaction_id': 'i4',
                    'drug_a': 'benztropine',
                    'drug_b': 'amitriptyline',
                    'severity': 'major',
                    'evidence': 'Cognitive impairment and delirium risk'}],
  'required_regimens': ['H_28-R1', 'H_28-R2'],
  'substitution_options': [{'regimen_id': 'H_28-R1',
                            'replace_drug': 'oxybutynin',
                            'with_drug': 'mirabegron',
                            'target_condition': 'incontinence',
                            'expected_risk_delta': 0.3,
                            'rationale': 'No anticholinergic effect'},
                           {'regimen_id': 'H_28-R2',
                            'replace_drug': 'amitriptyline',
                            'with_drug': 'sertraline',
                            'target_condition': 'depression',
                            'expected_risk_delta': 0.25,
                            'rationale': 'Lower anticholinergic burden'},
                           {'regimen_id': 'H_28-R3',
                            'replace_drug': 'benztropine',
                            'with_drug': 'levodopa',
                            'target_condition': 'parkinsonism',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Improved cognitive safety'}]},
 {'case_id': 'H_29',
  'template_family': 'train::thyroid-cardiac-cascade-002',
  'split': 'train',
  'age': 84,
  'labs': {'egfr': 54, 'creatinine': 1.3, 'potassium': 4.5, 'inr': 2.9},
  'diagnoses': ['hypothyroidism', 'atrial fibrillation'],
  'medications': ['levothyroxine', 'warfarin', 'amiodarone', 'metoprolol'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'levothyroxine',
                    'drug_b': 'warfarin',
                    'severity': 'major',
                    'evidence': 'Thyroid hormone increases warfarin sensitivity'},
                   {'interaction_id': 'i2',
                    'drug_a': 'amiodarone',
                    'drug_b': 'warfarin',
                    'severity': 'major',
                    'evidence': 'CYP inhibition increases INR'},
                   {'interaction_id': 'i3',
                    'drug_a': 'amiodarone',
                    'drug_b': 'levothyroxine',
                    'severity': 'moderate',
                    'evidence': 'Thyroid dysfunction risk'},
                   {'interaction_id': 'i4',
                    'drug_a': 'metoprolol',
                    'drug_b': 'amiodarone',
                    'severity': 'major',
                    'evidence': 'Bradycardia and conduction block'}],
  'required_regimens': ['H_29-R1', 'H_29-R2'],
  'substitution_options': [{'regimen_id': 'H_29-R1',
                            'replace_drug': 'warfarin',
                            'with_drug': 'apixaban',
                            'target_condition': 'af',
                            'expected_risk_delta': 0.25,
                            'rationale': 'Avoid INR fluctuations'},
                           {'regimen_id': 'H_29-R2',
                            'replace_drug': 'amiodarone',
                            'with_drug': 'dronedarone',
                            'target_condition': 'af',
                            'expected_risk_delta': 0.15,
                            'rationale': 'Lower thyroid toxicity'},
                           {'regimen_id': 'H_29-R3',
                            'replace_drug': 'metoprolol',
                            'with_drug': 'diltiazem',
                            'target_condition': 'rate control',
                            'expected_risk_delta': 0.1,
                            'rationale': 'Avoid additive bradycardia'}]},
 {'case_id': 'H_30',
  'template_family': 'validation::oncology-supportive-ddi-001',
  'split': 'validation',
  'age': 70,
  'labs': {'egfr': 46, 'creatinine': 1.6, 'potassium': 4.1, 'inr': 1.2, 'alt': 98, 'ast': 90},
  'diagnoses': ['cancer', 'nausea', 'infection'],
  'medications': ['ondansetron', 'aprepitant', 'dexamethasone', 'clarithromycin'],
  'interactions': [{'interaction_id': 'i1',
                    'drug_a': 'aprepitant',
                    'drug_b': 'dexamethasone',
                    'severity': 'major',
                    'evidence': 'CYP3A4 inhibition increases steroid exposure'},
                   {'interaction_id': 'i2',
                    'drug_a': 'clarithromycin',
                    'drug_b': 'aprepitant',
                    'severity': 'major',
                    'evidence': 'Increased aprepitant levels'},
                   {'interaction_id': 'i3',
                    'drug_a': 'clarithromycin',
                    'drug_b': 'ondansetron',
                    'severity': 'major',
                    'evidence': 'QT prolongation risk'},
                   {'interaction_id': 'i4',
                    'drug_a': 'ondansetron',
                    'drug_b': 'aprepitant',
                    'severity': 'moderate',
                    'evidence': 'Additive QT risk'}],
  'required_regimens': ['H_30-R1', 'H_30-R2'],
  'substitution_options': [{'regimen_id': 'H_30-R1',
                            'replace_drug': 'clarithromycin',
                            'with_drug': 'azithromycin',
                            'target_condition': 'infection',
                            'expected_risk_delta': 0.3,
                            'rationale': 'Lower CYP and QT interaction'},
                           {'regimen_id': 'H_30-R2',
                            'replace_drug': 'ondansetron',
                            'with_drug': 'palonosetron',
                            'target_condition': 'nausea',
                            'expected_risk_delta': 0.2,
                            'rationale': 'Lower QT prolongation'},
                           {'regimen_id': 'H_30-R3',
                            'replace_drug': 'dexamethasone',
                            'with_drug': 'dose reduction',
                            'target_condition': 'antiemetic regimen',
                            'expected_risk_delta': 0.1,
                            'rationale': 'Mitigate CYP3A4 interaction'}]}]

